"""Optional NVIDIA Qwen vision-reasoning transport."""

from .client import (
    NVIDIA_BASE_URL,
    NVIDIA_VISION_MODEL,
    NvidiaVisionClientConfig,
    NvidiaVisionResponse,
    NvidiaVisionTransport,
    redact_headers,
    validate_nvidia_base_url,
)
from .errors import (
    NvidiaAuthenticationError,
    NvidiaCancelledError,
    NvidiaCircuitOpenError,
    NvidiaConfigurationError,
    NvidiaModelUnavailableError,
    NvidiaPreprocessingError,
    NvidiaProviderUnavailableError,
    NvidiaRateLimitError,
    NvidiaResponseError,
    NvidiaSchemaError,
    NvidiaTimeoutError,
    NvidiaTransportError,
    NvidiaVisionError,
)
from .models import (
    NVIDIA_CONFIDENCE_SEMANTICS,
    NVIDIA_REASONING_SCHEMA_VERSION,
    NvidiaGeolocationReasoning,
    NvidiaLocationHypothesis,
    NvidiaObservedClue,
)
from .preprocessing import (
    CropKind,
    PreparedImage,
    PreparedImageSet,
    prepare_nvidia_images,
)
from .profiles import (
    NVIDIA_ACTIVE_VISION_MODEL,
    NVIDIA_DEPRECATED_VISION_MODEL,
    NVIDIA_VISION_MODEL_PROFILES,
    NvidiaVisionCapabilities,
    NvidiaVisionModelProfile,
    NvidiaVisionOutputMode,
    get_nvidia_vision_model_profile,
)
from .prompt import (
    NVIDIA_GEO_PROMPT_VERSION,
    NVIDIA_GEO_SYSTEM_PROMPT,
    build_nvidia_geo_user_prompt,
)
from .provider import (
    NvidiaCloudAuthorization,
    NvidiaProviderState,
    NvidiaProviderStatus,
    NvidiaStructuredResponse,
    NvidiaVisionProvider,
    build_nvidia_vision_provider,
)
from .reasoning import (
    NvidiaGeolocationReasoner,
    build_nvidia_geolocation_reasoner,
)

__all__ = [
    "NVIDIA_BASE_URL",
    "NVIDIA_ACTIVE_VISION_MODEL",
    "NVIDIA_CONFIDENCE_SEMANTICS",
    "NVIDIA_GEO_PROMPT_VERSION",
    "NVIDIA_GEO_SYSTEM_PROMPT",
    "NVIDIA_REASONING_SCHEMA_VERSION",
    "NVIDIA_DEPRECATED_VISION_MODEL",
    "NVIDIA_VISION_MODEL",
    "NVIDIA_VISION_MODEL_PROFILES",
    "CropKind",
    "NvidiaAuthenticationError",
    "NvidiaCancelledError",
    "NvidiaCircuitOpenError",
    "NvidiaCloudAuthorization",
    "NvidiaConfigurationError",
    "NvidiaGeolocationReasoner",
    "NvidiaGeolocationReasoning",
    "NvidiaLocationHypothesis",
    "NvidiaModelUnavailableError",
    "NvidiaObservedClue",
    "NvidiaPreprocessingError",
    "NvidiaProviderState",
    "NvidiaProviderStatus",
    "NvidiaProviderUnavailableError",
    "NvidiaRateLimitError",
    "NvidiaResponseError",
    "NvidiaSchemaError",
    "NvidiaStructuredResponse",
    "NvidiaTimeoutError",
    "NvidiaTransportError",
    "NvidiaVisionClientConfig",
    "NvidiaVisionCapabilities",
    "NvidiaVisionError",
    "NvidiaVisionProvider",
    "NvidiaVisionModelProfile",
    "NvidiaVisionOutputMode",
    "NvidiaVisionResponse",
    "NvidiaVisionTransport",
    "PreparedImage",
    "PreparedImageSet",
    "build_nvidia_vision_provider",
    "build_nvidia_geo_user_prompt",
    "build_nvidia_geolocation_reasoner",
    "prepare_nvidia_images",
    "get_nvidia_vision_model_profile",
    "redact_headers",
    "validate_nvidia_base_url",
]
