from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import Protocol

from atlaslens_api.retrieval.models import (
    Embedding,
    EmbeddingSpec,
    ImageMetadata,
    IndexMatch,
    ProviderDiagnostics,
    RetrievalHit,
)


class EmbeddingProvider(Protocol):
    @property
    def spec(self) -> EmbeddingSpec: ...

    @property
    def available(self) -> bool: ...

    @property
    def unavailable_reason(self) -> str | None: ...

    def embed(self, image_path: Path) -> Embedding: ...


class EmbeddingStorage(Protocol):
    @property
    def spec(self) -> EmbeddingSpec: ...

    @property
    def size(self) -> int: ...

    def append(self, ids: Sequence[int], embeddings: Sequence[Embedding]) -> None: ...

    def remove(self, ids: Sequence[int]) -> None: ...

    def persist(self) -> None: ...

    def reload(self) -> None: ...


class ImageIndex(EmbeddingStorage, Protocol):
    def search(self, embedding: Embedding, top_k: int) -> list[IndexMatch]: ...

    def ids(self) -> set[int]: ...

    def verify(self) -> ProviderDiagnostics: ...

    def diagnostics(self) -> ProviderDiagnostics: ...


class ImageMetadataRepository(Protocol):
    def initialize(self) -> None: ...

    def stage(self, metadata: Sequence[ImageMetadata]) -> tuple[list[ImageMetadata], int]: ...

    def activate(self, index_ids: Sequence[int]) -> None: ...

    def abort(self, index_ids: Sequence[int]) -> None: ...

    def discard(self, index_ids: Sequence[int]) -> None: ...

    def get_by_index_ids(self, index_ids: Sequence[int]) -> dict[int, ImageMetadata]: ...

    def active_index_ids(self) -> set[int]: ...

    def active_embedding_specs(self) -> set[tuple[str, str]]: ...

    def next_index_ids(self, count: int) -> list[int]: ...


class NearestNeighborEngine(Protocol):
    def retrieve(self, embedding: Embedding, top_k: int) -> list[RetrievalHit]: ...
