import type {
  AdjudicationDecision,
  CasePurpose,
  CaseSensitivity,
  CaseStatus,
  HypothesisOrigin,
} from "../api/schemas";
import type { Locale } from "../i18n";

export const LOCAL_ANALYST_ID = "local-analyst";

export const caseCopy = {
  en: {
    eyebrow: "Case and evidence workspace",
    listTitle: "Investigation cases",
    listIntro: "Review authorized visual evidence without treating model output as confirmed location.",
    createCase: "Create case",
    loadingCases: "Loading cases…",
    loadError: "Cases could not be loaded.",
    retry: "Try again",
    emptyTitle: "No investigation cases yet",
    emptyBody: "Create a case to record purpose, authorization, evidence provenance, and analyst decisions.",
    mediaCount: "media",
    hypothesesCount: "hypotheses",
    updated: "Updated",
    openCase: "Open case",
    createTitle: "Create investigation case",
    createIntro: "Record the legitimate purpose and source context before analyzing any media.",
    backToCases: "Back to cases",
    title: "Title",
    description: "Description (optional)",
    purpose: "Legitimate purpose",
    purposeDetail: "Purpose detail",
    sensitivity: "Sensitivity",
    sourceContext: "Source context",
    sourceContextHint: "Describe how the evidence was obtained without entering secrets or raw OCR.",
    retention: "Retention policy",
    authorization: "I attest that this investigation and its media are authorized.",
    localIdentity: "Local analyst seam; production authentication and tenant isolation are not enabled.",
    required: "This field is required.",
    purposeDetailRequired: "Explain the purpose when Other is selected.",
    authorizationRequired: "Authorization attestation is required.",
    saving: "Creating case…",
    createFailed: "The case could not be created.",
    conflictCreateWarning: "Conflict-related cases require heightened care. Exact model hypotheses remain unverified until analyst adjudication.",
    workspaceLoading: "Loading case workspace…",
    workspaceError: "The case workspace could not be loaded.",
    workspaceNotFound: "The requested case was not found.",
    status: "Status",
    casePurpose: "Purpose",
    caseSensitivity: "Sensitivity",
    evidenceMedia: "Media and analyses",
    addImage: "Add authorized image",
    chooseImage: "Choose image",
    imageAuthorization: "I am authorized to analyze this image.",
    analyzeAndLink: "Analyze and link",
    analyzing: "Analyzing and linking…",
    uploadFailed: "The image could not be analyzed and linked.",
    materializeFailed: "Completed analysis could not be materialized into case evidence.",
    retryMaterialize: "Retry evidence materialization",
    uploadPrivacy: "Uses the existing local-only analysis path. Raw pixels follow the configured temporary retention policy.",
    noMedia: "No media is linked to this case.",
    selectedAnalysis: "Selected analysis",
    analysisPending: "Analysis is still running.",
    analysisFailed: "Analysis failed safely; no location was asserted.",
    analysisComplete: "Analysis completed",
    analysisNotLinked: "No analysis is linked to this media.",
    mediaExpired: "The image is no longer available because of the retention policy.",
    evidenceTitle: "Normalized evidence",
    noEvidence: "No normalized evidence is available. AtlasLens abstains rather than inventing evidence.",
    provider: "Provider",
    providerFamily: "Provider family",
    provenance: "Provenance",
    hypothesesTitle: "Ranked location hypotheses",
    noHypotheses: "Not enough evidence for a location hypothesis.",
    modelCandidate: "Model candidate",
    operatorCorrection: "Operator correction",
    imported: "Imported hypothesis",
    unverified: "Unverified",
    accepted: "Accepted",
    rejected: "Rejected",
    needsEvidence: "More evidence required",
    withdrawn: "Withdrawn",
    uncalibrated: "Uncalibrated; this is not a probability.",
    notApplicable: "Confidence calibration is not applicable.",
    calibratedLabel: "Calibrated qualitative label",
    uncertainty: "Uncertainty radius",
    supportingEvidence: "Supporting evidence",
    modelFamilies: "Model families",
    rationale: "Decision rationale",
    rationaleRequired: "A rationale is required for an append-only adjudication.",
    accept: "Accept",
    reject: "Reject",
    requestEvidence: "Require more evidence",
    decisionFailed: "The adjudication could not be appended.",
    correctionTitle: "Add operator-corrected location",
    correctionIntro: "Creates a separate hypothesis; the original model output is never overwritten.",
    latitude: "Latitude",
    longitude: "Longitude",
    radius: "Uncertainty radius (metres)",
    country: "Country code (optional)",
    region: "Region (optional)",
    locality: "Locality (optional)",
    initialDecision: "Initial adjudication",
    addCorrection: "Add operator correction",
    correctionFailed: "The operator correction could not be added.",
    auditTitle: "Tamper-evident application history",
    auditValid: "Audit hash chain verified",
    auditInvalid: "Audit integrity check failed",
    auditLegal: "Application history is tamper-evident; it is not legally certified evidence.",
    noAudit: "No audit events were returned.",
    event: "Event",
    actor: "Actor",
    conflictWarning: "Sensitive-use warning: this conflict-related case may affect vulnerable people. Exact hypotheses remain visibly unverified until an analyst adjudicates them. Do not use AtlasLens for real-time tactical targeting.",
    mapTitle: "Hypothesis map",
    mapHelp: "Map markers show hypotheses and positive uncertainty radii, not confirmed locations.",
    mapUnavailable: "Interactive map unavailable. The textual hypothesis list remains authoritative.",
    invalidFile: "Choose a valid JPEG, PNG, or WebP image within the server limit.",
  },
  tr: {
    eyebrow: "Vaka ve kanıt çalışma alanı",
    listTitle: "İnceleme vakaları",
    listIntro: "Yetkili görsel kanıtı, model çıktısını doğrulanmış konum saymadan inceleyin.",
    createCase: "Vaka oluştur",
    loadingCases: "Vakalar yükleniyor…",
    loadError: "Vakalar yüklenemedi.",
    retry: "Yeniden dene",
    emptyTitle: "Henüz inceleme vakası yok",
    emptyBody: "Amaç, yetkilendirme, kanıt kaynağı ve analist kararlarını kaydetmek için vaka oluşturun.",
    mediaCount: "medya",
    hypothesesCount: "hipotez",
    updated: "Güncellendi",
    openCase: "Vakayı aç",
    createTitle: "İnceleme vakası oluştur",
    createIntro: "Herhangi bir medyayı analiz etmeden önce meşru amacı ve kaynak bağlamını kaydedin.",
    backToCases: "Vakalara dön",
    title: "Başlık",
    description: "Açıklama (isteğe bağlı)",
    purpose: "Meşru amaç",
    purposeDetail: "Amaç ayrıntısı",
    sensitivity: "Hassasiyet",
    sourceContext: "Kaynak bağlamı",
    sourceContextHint: "Kanıtın nasıl elde edildiğini sır veya ham OCR içeriği girmeden açıklayın.",
    retention: "Saklama politikası",
    authorization: "Bu incelemenin ve medyanın yetkili olduğunu beyan ederim.",
    localIdentity: "Yerel analist sınırı; üretim kimlik doğrulaması ve kiracı yalıtımı etkin değildir.",
    required: "Bu alan zorunludur.",
    purposeDetailRequired: "Diğer seçildiğinde amacı açıklayın.",
    authorizationRequired: "Yetkilendirme beyanı zorunludur.",
    saving: "Vaka oluşturuluyor…",
    createFailed: "Vaka oluşturulamadı.",
    conflictCreateWarning: "Çatışmayla ilgili vakalar yüksek özen gerektirir. Kesin model hipotezleri analist kararı verilene kadar doğrulanmamış kalır.",
    workspaceLoading: "Vaka çalışma alanı yükleniyor…",
    workspaceError: "Vaka çalışma alanı yüklenemedi.",
    workspaceNotFound: "İstenen vaka bulunamadı.",
    status: "Durum",
    casePurpose: "Amaç",
    caseSensitivity: "Hassasiyet",
    evidenceMedia: "Medya ve analizler",
    addImage: "Yetkili görsel ekle",
    chooseImage: "Görsel seç",
    imageAuthorization: "Bu görseli analiz etmeye yetkiliyim.",
    analyzeAndLink: "Analiz et ve bağla",
    analyzing: "Analiz ediliyor ve bağlanıyor…",
    uploadFailed: "Görsel analiz edilip vakaya bağlanamadı.",
    materializeFailed: "Tamamlanan analiz vaka kanıtına dönüştürülemedi.",
    retryMaterialize: "Kanıt oluşturmayı yeniden dene",
    uploadPrivacy: "Mevcut yalnızca-yerel analiz yolunu kullanır. Ham pikseller yapılandırılmış geçici saklama politikasına tabidir.",
    noMedia: "Bu vakaya bağlı medya yok.",
    selectedAnalysis: "Seçili analiz",
    analysisPending: "Analiz hâlâ çalışıyor.",
    analysisFailed: "Analiz güvenli biçimde başarısız oldu; konum ileri sürülmedi.",
    analysisComplete: "Analiz tamamlandı",
    analysisNotLinked: "Bu medyaya bağlı analiz yok.",
    mediaExpired: "Görsel saklama politikası gereği artık mevcut değil",
    evidenceTitle: "Normalize edilmiş kanıt",
    noEvidence: "Normalize edilmiş kanıt yok. AtlasLens kanıt uydurmak yerine çekimser kalır.",
    provider: "Sağlayıcı",
    providerFamily: "Sağlayıcı ailesi",
    provenance: "Kaynak geçmişi",
    hypothesesTitle: "Sıralı konum hipotezleri",
    noHypotheses: "Konum hipotezi için yeterli kanıt yok.",
    modelCandidate: "Model adayı",
    operatorCorrection: "Operatör düzeltmesi",
    imported: "İçe aktarılan hipotez",
    unverified: "Doğrulanmamış",
    accepted: "Kabul edildi",
    rejected: "Reddedildi",
    needsEvidence: "Daha fazla kanıt gerekli",
    withdrawn: "Geri çekildi",
    uncalibrated: "Kalibre edilmemiştir; bu bir olasılık değildir.",
    notApplicable: "Güven kalibrasyonu uygulanamaz.",
    calibratedLabel: "Kalibre edilmiş nitel etiket",
    uncertainty: "Belirsizlik yarıçapı",
    supportingEvidence: "Destekleyen kanıt",
    modelFamilies: "Model aileleri",
    rationale: "Karar gerekçesi",
    rationaleRequired: "Salt-eklemeli değerlendirme için gerekçe zorunludur.",
    accept: "Kabul et",
    reject: "Reddet",
    requestEvidence: "Daha fazla kanıt iste",
    decisionFailed: "Değerlendirme eklenemedi.",
    correctionTitle: "Operatör tarafından düzeltilmiş konum ekle",
    correctionIntro: "Ayrı bir hipotez oluşturur; özgün model çıktısının üzerine yazılmaz.",
    latitude: "Enlem",
    longitude: "Boylam",
    radius: "Belirsizlik yarıçapı (metre)",
    country: "Ülke kodu (isteğe bağlı)",
    region: "Bölge (isteğe bağlı)",
    locality: "Yerleşim (isteğe bağlı)",
    initialDecision: "İlk değerlendirme",
    addCorrection: "Operatör düzeltmesi ekle",
    correctionFailed: "Operatör düzeltmesi eklenemedi.",
    auditTitle: "Kurcalamaya duyarlı uygulama geçmişi",
    auditValid: "Denetim özet zinciri doğrulandı",
    auditInvalid: "Denetim bütünlüğü kontrolü başarısız",
    auditLegal: "Uygulama geçmişi kurcalamaya duyarlıdır; hukuken sertifikalı kanıt değildir.",
    noAudit: "Denetim olayı döndürülmedi.",
    event: "Olay",
    actor: "Aktör",
    conflictWarning: "Hassas kullanım uyarısı: Çatışmayla ilgili bu vaka savunmasız kişileri etkileyebilir. Kesin hipotezler analist değerlendirmesine kadar görünür biçimde doğrulanmamış kalır. AtlasLens'i gerçek zamanlı taktik hedefleme için kullanmayın.",
    mapTitle: "Hipotez haritası",
    mapHelp: "Harita işaretleri hipotezleri ve pozitif belirsizlik yarıçaplarını gösterir; doğrulanmış konumları değil.",
    mapUnavailable: "Etkileşimli harita kullanılamıyor. Metinsel hipotez listesi yetkili görünüm olmaya devam eder.",
    invalidFile: "Sunucu sınırındaki geçerli bir JPEG, PNG veya WebP görsel seçin.",
  },
} as const;

export function purposeLabel(value: CasePurpose, locale: Locale): string {
  const labels: Record<CasePurpose, Record<Locale, string>> = {
    journalism: { en: "Journalism", tr: "Gazetecilik" },
    humanitarian: { en: "Humanitarian", tr: "İnsani yardım" },
    disaster_response: { en: "Disaster response", tr: "Afet müdahalesi" },
    insurance: { en: "Insurance", tr: "Sigorta" },
    authorized_security_research: { en: "Authorized security research", tr: "Yetkili güvenlik araştırması" },
    other: { en: "Other", tr: "Diğer" },
  };
  return labels[value][locale];
}

export function statusLabel(value: CaseStatus, locale: Locale): string {
  const labels: Record<CaseStatus, Record<Locale, string>> = {
    open: { en: "Open", tr: "Açık" },
    under_review: { en: "Under review", tr: "İnceleniyor" },
    resolved: { en: "Resolved", tr: "Çözüldü" },
    archived: { en: "Archived", tr: "Arşivlendi" },
  };
  return labels[value][locale];
}

export function sensitivityLabel(value: CaseSensitivity, locale: Locale): string {
  const labels: Record<CaseSensitivity, Record<Locale, string>> = {
    standard: { en: "Standard", tr: "Standart" },
    sensitive: { en: "Sensitive", tr: "Hassas" },
    conflict_related: { en: "Conflict-related", tr: "Çatışmayla ilgili" },
  };
  return labels[value][locale];
}

export function originLabel(value: HypothesisOrigin, locale: Locale): string {
  const text = caseCopy[locale];
  if (value === "model") return text.modelCandidate;
  if (value === "operator_correction") return text.operatorCorrection;
  return text.imported;
}

export function decisionLabel(value: AdjudicationDecision | null, locale: Locale): string {
  const text = caseCopy[locale];
  if (value === "accepted") return text.accepted;
  if (value === "rejected") return text.rejected;
  if (value === "needs_more_evidence") return text.needsEvidence;
  if (value === "withdrawn") return text.withdrawn;
  return text.unverified;
}
