import { execFileSync } from "node:child_process";
import { mkdirSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { expect, test, type Page } from "@playwright/test";

const apiBaseUrl = process.env.ATLASLENS_E2E_API_URL ?? "http://127.0.0.1:8100";
const apiProject = fileURLToPath(new URL("../../../services/api", import.meta.url));
const apiPython = process.env.ATLASLENS_E2E_PYTHON ?? resolve(
  apiProject,
  ".venv",
  process.platform === "win32" ? "Scripts/python.exe" : "bin/python",
);

function captureBrowserErrors(page: Page): string[] {
  const errors: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error") errors.push(message.text());
  });
  page.on("pageerror", (error) => errors.push(error.message));
  return errors;
}

function generateKnownExifFixture(): string {
  const output = fileURLToPath(new URL("../test-results/known-exif.jpg", import.meta.url));
  mkdirSync(fileURLToPath(new URL("../test-results", import.meta.url)), { recursive: true });
  const script = `
import sys
import piexif
from PIL import Image

def dms(value):
    absolute = abs(value)
    degrees = int(absolute)
    minutes_float = (absolute - degrees) * 60
    minutes = int(minutes_float)
    seconds = (minutes_float - minutes) * 60
    return ((degrees, 1), (minutes, 1), (round(seconds * 100000), 100000))

latitude = 41.0082
longitude = 28.9784
exif = {
    "0th": {piexif.ImageIFD.Orientation: 1},
    "GPS": {
        piexif.GPSIFD.GPSLatitudeRef: b"N",
        piexif.GPSIFD.GPSLatitude: dms(latitude),
        piexif.GPSIFD.GPSLongitudeRef: b"E",
        piexif.GPSIFD.GPSLongitude: dms(longitude),
        piexif.GPSIFD.GPSAltitudeRef: 0,
        piexif.GPSIFD.GPSAltitude: (125, 10),
    },
}
image = Image.new("RGB", (96, 72), (92, 118, 132))
image.save(sys.argv[1], "JPEG", quality=90, exif=piexif.dump(exif))
`;
  execFileSync(apiPython, ["-c", script, output], { cwd: apiProject, stdio: "pipe" });
  return output;
}

function generateNoExifFixture(): string {
  const output = fileURLToPath(new URL("../test-results/no-exif.jpg", import.meta.url));
  mkdirSync(fileURLToPath(new URL("../test-results", import.meta.url)), { recursive: true });
  const script = `
import sys
from PIL import Image
Image.new("RGB", (96, 72), (72, 96, 112)).save(sys.argv[1], "JPEG", quality=90)
`;
  execFileSync(apiPython, ["-c", script, output], { cwd: apiProject, stdio: "pipe" });
  return output;
}

async function installPhase4Fixture(page: Page, supported: boolean): Promise<void> {
  const id = supported ? "00000000-0000-4000-8000-000000000041" : "00000000-0000-4000-8000-000000000042";
  const hitId = "00000000-0000-4000-8000-000000000043";
  const candidate = {
    id: "generated-fixture-candidate",
    rank: 1,
    center: { latitude: 0, longitude: 0 },
    geometry: { type: "Point", coordinates: [0, 0] },
    radius_km: 25,
    uncertainty_basis: "generated fixture only",
    confidence: 0.35,
    confidence_kind: "uncalibrated_score",
    confidence_basis: "generated fixture; not a probability",
    granularity: "broad_area",
    country_code: null,
    label: "Generated licensed fixture",
    source: "generated-test-fixture",
    evidence_ids: ["fixture-evidence"],
    evidence_summary: "Generated transformation is visually consistent with its licensed fixture.",
    provenance: [{ provider_id: "opencv_orb", provider_kind: "geometry", provider_version: "phase4-v1", execution_boundary: "local", model_name: null, output_schema_version: "1" }],
    verification_status: "unverified_model",
    verified: false,
    phase4_assessment: {
      classification: "geometry_supported",
      relative_rank_score: 0.72,
      score_semantics: "uncalibrated_relative_rank",
      reranker_version: "phase4-v1",
      score_breakdown: [{ feature: "geometry_inliers", raw_value: 0.8, weight: 0.2, contribution: 0.16, reason_code: "generated_fixture_support" }],
      source_diversity: 1,
      contributing_retrieval_hit_ids: [hitId],
      map_observations: [],
      geometry_results: [{ reference_id: hitId, provider: "opencv_orb", status: "supported", query_keypoints: 120, reference_keypoints: 118, raw_matches: 70, filtered_matches: 40, inliers: 32, inlier_ratio: 0.8, query_coverage: 0.4, reference_coverage: 0.38, residual_error_px: 0.9, robust_model_type: "homography", limitations: ["visual consistency is not geographic proof"], runtime_ms: 12 }],
      contradictions: [],
      reference_attributions: [{ reference_id: hitId, source: "generated-test-fixture", license: "CC0-1.0", attribution: "Generated by the AtlasLens test suite", display_allowed: false }],
      limitations: ["visual consistency is not geographic proof"],
    },
  };
  const analysis = {
    id,
    status: "completed",
    analysis_mode: "local_only",
    created_at: "2026-07-11T00:00:00Z",
    expires_at: "2026-07-11T01:00:00Z",
    progress: { stage: "completed", percent: 100, message_key: "analysis.completed" },
    image: { format: "jpeg", width: 96, height: 72, megapixels: 0.01, sha256: "0".repeat(64), orientation_normalized: true, exif_present: false },
    quality: { blur_score: 0.8, brightness_score: 0.6, contrast_score: 0.7, resolution_score: 0.5, warnings: [] },
    evidence: supported ? [{ id: "fixture-evidence", type: "system", label: "generated_fixture", display_value: "Generated test fixture", confidence: 0.35, confidence_basis: "test fixture support", source: "generated-test-fixture", sensitive: false, provenance: candidate.provenance[0] }] : [],
    candidates: supported ? [candidate] : [],
    abstention: supported ? null : { abstained: true, reason_code: "geometry_inconclusive", message_key: "analysis.insufficient_geographic_evidence" },
    warnings: [],
    timings_ms: { total: 12 },
    fusion_policy_version: "phase4-fixture",
    result_classification: "real",
    provider_comparisons: supported ? [{
      provider_id: "atlaslens-custom-v1",
      mode: "shadow",
      status: "succeeded",
      runtime_ms: 18,
      distance_to_primary_km: 420,
      candidate_overlap: 0,
      ranking_impact: "none",
      failure_code: null,
    }] : [],
    failure: null,
  };
  await page.route("**/api/v1/analyses", async (route) => {
    if (route.request().method() !== "POST") return route.fallback();
    await route.fulfill({ status: 202, contentType: "application/json", body: JSON.stringify({ id, status: "queued", status_url: `/api/v1/analyses/${id}`, events_url: `/api/v1/analyses/${id}/events`, delete_url: `/api/v1/analyses/${id}` }) });
  });
  await page.route(`**/api/v1/analyses/${id}/events`, (route) => route.fulfill({
    status: 200,
    contentType: "text/event-stream",
    body: `event: completed\ndata: ${JSON.stringify({ event_id: "fixture-terminal", event_type: "completed", analysis_id: id, occurred_at: "2026-07-11T00:00:01Z", status: "completed", progress: { stage: "completed", percent: 100, message_key: "analysis.completed" } })}\n\n`,
  }));
  await page.route(`**/api/v1/analyses/${id}`, async (route) => {
    if (route.request().method() === "DELETE") return route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ id, deleted: true }) });
    await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(analysis) });
  });
}

test("known EXIF upload renders a real candidate and can be deleted", async ({ page, request }) => {
  const browserErrors = captureBrowserErrors(page);
  const fixture = generateKnownExifFixture();
  await page.goto("/");
  await expect(page.getByText("Analysis service available")).toBeVisible();

  await page.getByTestId("file-input").setInputFiles(fixture);
  await page.getByRole("checkbox", { name: /I own this image/ }).check();
  const createResponse = page.waitForResponse(
    (response) => response.request().method() === "POST" && new URL(response.url()).pathname === "/api/v1/analyses",
  );
  const analyze = page.getByRole("button", { name: "Analyze photo" });
  await expect(analyze).toBeEnabled();
  await analyze.click();
  const response = await createResponse;
  expect(response.status()).toBe(202);
  const accepted = (await response.json()) as { id: string };

  await expect(page.getByRole("heading", { name: "Candidate regions" })).toBeVisible({ timeout: 20_000 });
  await expect(page.getByRole("heading", { name: "Candidate 1" })).toBeVisible();
  await expect(page.getByText("Source-derived support").first()).toBeVisible();
  await expect(page.getByTestId("map-region")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Textual map alternative" })).toBeVisible();

  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);

  await page.getByRole("button", { name: "Delete analysis" }).click();
  await expect(page.getByText("Analysis deleted from the server.")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Candidate 1" })).toHaveCount(0);
  const deleted = await request.get(`${apiBaseUrl}/api/v1/analyses/${accepted.id}`);
  expect(deleted.status()).toBe(404);
  expect(browserErrors).toEqual([]);
});

test("no-EXIF upload returns 202 and safely abstains", async ({ page, request }) => {
  const browserErrors = captureBrowserErrors(page);
  const fixture = generateNoExifFixture();
  await page.goto("/");
  await expect(page.getByText("Analysis service available")).toBeVisible();

  await page.getByTestId("file-input").setInputFiles(fixture);
  await page.getByRole("checkbox", { name: /I own this image/ }).check();
  const createResponse = page.waitForResponse(
    (response) => response.request().method() === "POST" && new URL(response.url()).pathname === "/api/v1/analyses",
  );
  await page.getByRole("button", { name: "Analyze photo" }).click();
  const response = await createResponse;
  expect(response.status()).toBe(202);
  const accepted = (await response.json()) as { id: string };

  await expect(page.getByRole("heading", { name: "Not enough evidence to estimate a location" })).toBeVisible({ timeout: 20_000 });
  await expect(page.getByText(/did not invent one/)).toBeVisible();
  await page.getByRole("button", { name: "Delete analysis" }).click();
  await expect(page.getByText("Analysis deleted from the server.")).toBeVisible();
  const deleted = await request.get(`${apiBaseUrl}/api/v1/analyses/${accepted.id}`);
  expect(deleted.status()).toBe(404);
  expect(browserErrors).toEqual([]);
});

test("generated licensed fixture renders geometry support as an uncalibrated diagnostic", async ({ page }) => {
  const browserErrors = captureBrowserErrors(page);
  await installPhase4Fixture(page, true);
  await page.goto("/");
  await page.getByTestId("file-input").setInputFiles(generateNoExifFixture());
  await page.getByRole("checkbox", { name: /I own this image/ }).check();
  await page.getByRole("button", { name: "Analyze photo" }).click();
  await page.getByText("Advanced diagnostics and raw relative scores").click();
  await expect(page.getByRole("heading", { name: "Candidate assessment" })).toBeVisible();
  await expect(page.getByText("0.720")).toBeVisible();
  await expect(page.getByText(/not a probability or a location guarantee/)).toBeVisible();
  await expect(page.getByRole("heading", { name: "Provider comparison" })).toBeVisible();
  await expect(page.getByText("atlaslens-custom-v1")).toBeVisible();
  await expect(page.getByText(/Shadow.*Succeeded.*420 km/)).toBeVisible();
  await expect(page.getByText(/Reference display denied by policy/)).toBeVisible();
  await expect(page.getByRole("img")).toHaveCount(0);
  expect(browserErrors).toEqual([]);
});

test("unrelated generated fixture abstains without false geometry support", async ({ page }) => {
  const browserErrors = captureBrowserErrors(page);
  await installPhase4Fixture(page, false);
  await page.goto("/");
  await page.getByTestId("file-input").setInputFiles(generateNoExifFixture());
  await page.getByRole("checkbox", { name: /I own this image/ }).check();
  await page.getByRole("button", { name: "Analyze photo" }).click();
  await expect(page.getByRole("heading", { name: "Not enough evidence to estimate a location" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Candidate assessment" })).toHaveCount(0);
  expect(browserErrors).toEqual([]);
});
