import { z } from "zod";
import type { components } from "./generated";

type GeneratedCapabilities = components["schemas"]["CapabilitiesResponse"];
export type ProviderCapability = components["schemas"]["ProviderCapability"];
export type Capabilities = Omit<GeneratedCapabilities, "providers"> & {
  providers: {
    exif: ProviderCapability;
    quality: ProviderCapability;
    ocr: ProviderCapability;
    cloud_vision: ProviderCapability;
    global_geolocation?: ProviderCapability;
    embedding?: ProviderCapability;
    retrieval?: ProviderCapability;
    place_research?: ProviderCapability;
    map_research?: ProviderCapability;
    visual_clues?: ProviderCapability;
    [provider: string]: ProviderCapability | undefined;
  };
};
type GeneratedAnalysis = components["schemas"]["Analysis"];
export type AnalysisAccepted = components["schemas"]["AnalysisAccepted"];
export type AnalysisEvent = components["schemas"]["AnalysisEvent"];
export type AnalysisMode = components["schemas"]["AnalysisMode"];
type GeneratedCandidate = components["schemas"]["Candidate"];
export type Evidence = components["schemas"]["Evidence"];
export type RetrievalCoverageContext = components["schemas"]["RetrievalCoverageContext"];
export type ProblemDetails = components["schemas"]["ProblemDetails"];
export type Progress = components["schemas"]["Progress"];
type RequireFields<T, K extends keyof T> = T & Required<Pick<T, K>>;
export type Phase4Assessment = RequireFields<components["schemas"]["Phase4Assessment"], "map_observations" | "geometry_results" | "contradictions" | "reference_attributions" | "limitations">;
export type Phase5BAssessment = RequireFields<components["schemas"]["Phase5BAssessment"], "place_matches" | "retrieval_matches" | "map_observations" | "supports" | "contradictions" | "movement_reasons" | "limitations">;
export type Phase5BDiagnostics = RequireFields<components["schemas"]["Phase5BDiagnostics"], "partial_failures">;
export type ModelPredictionDiagnostics = components["schemas"]["ModelPredictionDiagnostics"];
type GeneratedProviderStatusResponse = components["schemas"]["ProviderStatusResponse"];
type GeneratedProviderStatusItem = components["schemas"]["ProviderStatusItem"];
export type ProviderStatusItem = GeneratedProviderStatusItem & {
  source_family?: string | null;
  selected_specialization?: string | null;
  execution_mode?: "in_process" | "isolated_worker" | null;
  source_revision?: string | null;
  weights_available?: boolean | null;
  usable?: boolean | null;
  load_error?: string | null;
  key_configured?: boolean | null;
  budget_available?: boolean | null;
};
export type ProviderStatusResponse = Omit<GeneratedProviderStatusResponse, "providers"> & {
  providers: ProviderStatusItem[];
};
export type ModelStatusResponse = components["schemas"]["ModelStatusResponse"];
export type ModelStatusItem = components["schemas"]["ModelStatusItem"];
export type AnalysisHistoryPage = components["schemas"]["AnalysisHistoryPage"];
export type AnalysisHistoryItem = components["schemas"]["AnalysisHistoryItem"];
export type EvaluationReportList = Omit<components["schemas"]["EvaluationReportList"], "reports"> & { reports: EvaluationReportSummary[] };
type EvaluationRatioView = RequireFields<components["schemas"]["RatioView"], "numerator" | "denominator" | "value">;
export type EvaluationReportSummary = Omit<components["schemas"]["EvaluationReportSummary"], "country_top1" | "country_top5" | "region_top1" | "city_top1" | "recall_top1" | "abstention" | "provider_failure" | "uncertainty_coverage"> & {
  country_top1: EvaluationRatioView;
  country_top5: EvaluationRatioView;
  region_top1: EvaluationRatioView;
  city_top1: EvaluationRatioView;
  recall_top1: Record<string, EvaluationRatioView>;
  abstention: EvaluationRatioView;
  provider_failure: EvaluationRatioView;
  uncertainty_coverage: EvaluationRatioView;
};
export type DatasetQAReportList = components["schemas"]["DatasetQAReportList"];
export type DatasetQAReportSummary = components["schemas"]["DatasetQAReportSummary"];
export type DatasetQAReport = components["schemas"]["DatasetQAReport"];

// Handwritten until the Phase 2 OpenAPI client is regenerated by the integration owner.
export type CasePurpose =
  | "journalism"
  | "humanitarian"
  | "disaster_response"
  | "insurance"
  | "authorized_security_research"
  | "other";
export type CaseStatus = "open" | "under_review" | "resolved" | "archived";
export type CaseSensitivity = "standard" | "sensitive" | "conflict_related";
export type CaseStorageState = "ephemeral" | "deleted_after_analysis" | "unavailable" | "externally_managed";
export type HypothesisOrigin = "model" | "operator_correction" | "imported";
export type HypothesisCalibrationState = "calibrated" | "uncalibrated" | "not_applicable";
export type AdjudicationDecision = "accepted" | "rejected" | "needs_more_evidence" | "withdrawn";

export interface InvestigationCase {
  id: string;
  workspace_id: string;
  title: string;
  description: string | null;
  purpose: CasePurpose;
  purpose_detail: string | null;
  source_context: string;
  status: CaseStatus;
  sensitivity: CaseSensitivity;
  authorization_attested: boolean;
  retention_policy: string;
  created_at: string;
  updated_at: string;
  closed_at: string | null;
  created_by_actor_id: string;
  version: number;
  media_count: number;
  evidence_count: number;
  hypothesis_count: number;
  adjudication_count: number;
  latest_adjudication_decision: AdjudicationDecision | null;
}

export interface CasePage {
  items: InvestigationCase[];
  total: number;
  limit: number;
  offset: number;
  ordering: "updated_at_desc_id_desc";
}

export interface CaseMedia {
  id: string;
  case_id: string;
  analysis_id: string | null;
  media_type: "image";
  source_type: "upload" | "source_url" | "external_archive" | "other";
  original_filename_display: string;
  mime_type: string;
  byte_size: number;
  sha256: string;
  captured_at: string | null;
  received_at: string;
  source_url: string | null;
  archive_url: string | null;
  source_description: string | null;
  authorization_attested: boolean;
  storage_state: CaseStorageState;
  created_at: string;
  analysis_status_at_link: string | null;
  analysis_created_at: string | null;
  analysis_expires_at: string | null;
  materialized_at: string | null;
}

export interface CaseMediaPage {
  items: CaseMedia[];
  total: number;
  limit: number;
  offset: number;
  ordering: "created_at_asc_id_asc";
}

export interface CaseEvidenceRecord {
  id: string;
  case_id: string;
  media_id: string;
  analysis_id: string;
  evidence_type: "metadata" | "ocr" | "visual_clue" | "model_hypothesis" | "retrieval_match" | "map_evidence" | "analyst_note";
  provider: string;
  provider_family: string;
  summary: string;
  structured_payload: Record<string, unknown>;
  provenance: Record<string, unknown>;
  observed_at: string;
  created_at: string;
  immutable_source_hash: string;
}

export interface CaseEvidencePage {
  items: CaseEvidenceRecord[];
  total: number;
  limit: number;
  offset: number;
  ordering: "created_at_asc_id_asc";
}

export interface CaseAdjudication {
  id: string;
  case_id: string;
  hypothesis_id: string;
  actor_id: string;
  decision: AdjudicationDecision;
  rationale: string;
  created_at: string;
  supersedes_adjudication_id: string | null;
}

export interface LocationHypothesis {
  id: string;
  case_id: string;
  media_id: string;
  analysis_id: string | null;
  origin: HypothesisOrigin;
  latitude: number;
  longitude: number;
  uncertainty_radius_m: number;
  country_code: string | null;
  region_name: string | null;
  locality_name: string | null;
  rank: number | null;
  confidence_label: string | null;
  calibration_state: HypothesisCalibrationState;
  supporting_evidence_ids: string[];
  model_family_groups: string[];
  created_at: string;
  supersedes_hypothesis_id: string | null;
  latest_adjudication: CaseAdjudication | null;
  adjudications: CaseAdjudication[];
  adjudication_count: number;
}

export interface CaseHypothesisPage {
  items: LocationHypothesis[];
  total: number;
  limit: number;
  offset: number;
  ordering: "created_at_asc_id_asc";
}

export interface CaseAuditEvent {
  id: string;
  case_id: string;
  sequence_number: number;
  event_type: string;
  actor_id: string;
  actor_type: "operator" | "system" | "model";
  payload: Record<string, unknown>;
  created_at: string;
  previous_event_hash: string | null;
  event_hash: string;
}

export interface CaseAuditEventPage {
  items: CaseAuditEvent[];
  total: number;
  limit: number;
  offset: number;
  ordering: "sequence_number_asc";
  integrity_scope: "tamper_evident_application_history";
}

export interface CaseAuditIntegrity {
  case_id: string;
  valid: boolean;
  checked_event_count: number;
  first_invalid_sequence: number | null;
  reason: string | null;
  integrity_scope: "tamper_evident_application_history";
  legally_certified_evidence: false;
}

export interface CaseMaterializationResult {
  case_id: string;
  media_id: string;
  analysis_id: string;
  created: boolean;
  evidence_created: number;
  hypotheses_created: number;
  already_materialized: boolean;
  evidence_ids: string[];
  hypothesis_ids: string[];
}

export interface OperatorHypothesisResult {
  hypothesis: LocationHypothesis;
  adjudication: CaseAdjudication;
}

export interface SceneClassSummary {
  class_id: number;
  class_name: string;
  pixel_ratio: number;
  percentage: number;
}

export interface SceneGroupSummary {
  name: string;
  pixel_ratio: number;
  percentage: number;
}

export interface SceneTagSummary {
  name: string;
  strength: number;
  strength_semantics: "deterministic_heuristic_not_probability";
  reason: string;
}

export interface SceneSegmentationSummary {
  status: "completed";
  provider: string;
  device: string;
  inference_ms: number;
  image_width: number;
  image_height: number;
  semantic_label_names_available: boolean;
  dominant_classes: SceneClassSummary[];
  scene_groups: SceneGroupSummary[];
  scene_tags: SceneTagSummary[];
  warnings: string[];
}

export interface GeoClipClusterSummary {
  cluster_id: string;
  source: "geoclip";
  member_count: number;
  member_ranks: number[];
  max_raw_similarity: number;
  mean_raw_similarity: number;
  raw_score_type: string;
  cluster_support: number;
  score_semantics: "uncalibrated_relative_rank";
}

export interface UncalibratedConfidenceSummary {
  label: "low" | "medium" | "high" | "very_high";
  score: null;
  calibrated: false;
  basis: string[];
}

export interface ReverseGeocodeSummary {
  country: string | null;
  country_code: string | null;
  region: string | null;
  city: string | null;
  district: string | null;
  display_name: string;
  provider: string;
  dataset_version: string;
  license: string;
}

export type Phase6BProviderState = "completed" | "skipped" | "disabled" | "failed" | "timeout";
export type Phase6BSourceFamily =
  | "mp16_family"
  | "osv5m_family"
  | "yfcc_family"
  | "inat_family"
  | "textual_evidence_family"
  | "cloud_reasoning_family";

export interface Phase6BGeographicCandidateSummary {
  candidate_id: string;
  latitude: number;
  longitude: number;
  raw_score: number | null;
  provider_rank: number;
  sample_support: number;
  metadata?: Record<string, string | number | boolean | null>;
}

export interface Phase6BModelPredictionSummary {
  provider: string;
  model_id: string;
  model_revision: string;
  source_family: Phase6BSourceFamily;
  status: Phase6BProviderState;
  device: "cuda" | "cpu";
  duration_ms: number;
  score_semantics: "similarity" | "direct_regression" | "sample_density";
  candidates: Phase6BGeographicCandidateSummary[];
  warnings: string[];
  reason_code?: string | null;
  execution_mode?: "in_process" | "isolated_worker" | null;
  diagnostics?: Record<string, string | number | boolean | null>;
}

export interface Phase6BFusionMemberSummary {
  provider: string;
  model_id: string;
  source_family: Phase6BSourceFamily;
  provider_rank: number;
  candidate_id?: string;
  sample_support?: number;
}

export interface Phase6BFusionContributionSummary {
  name: string;
  contribution: number;
  reason: string;
  raw_value?: number;
  weight?: number;
}

export interface Phase6BFusedClusterSummary {
  cluster_id: string;
  latitude: number;
  longitude: number;
  radius_km: number;
  relative_rank_score?: number;
  score_semantics?: "uncalibrated_relative_rank_not_probability";
  provider_count: number;
  independent_family_count: number;
  same_family_duplicate_support: number;
  spread_km: number;
  members: Phase6BFusionMemberSummary[];
  contributions: Phase6BFusionContributionSummary[];
  ocr_agreement: boolean;
  ocr_contradiction: boolean;
}

export interface Phase6BAgreementSummary {
  provider_count: number;
  independent_family_count: number;
  same_family_duplicate_support: number;
  geographic_disagreement: boolean;
  ocr_agreement: boolean;
  ocr_contradiction: boolean;
}

export interface Phase6BFusionSummary {
  version: "phase6b-v1";
  source_families: Phase6BSourceFamily[];
  agreement_summary: Phase6BAgreementSummary;
  candidate_clusters: Phase6BFusedClusterSummary[];
  provider_failures?: string[];
  abstained?: boolean;
  warnings?: string[];
}

export interface Phase6BOCRDetectionSummary {
  redacted_text: string;
  normalized_text?: string;
  confidence: number;
  confidence_semantics?: "uncalibrated_ocr_engine_score";
  script: string;
  provider: string;
  profile: string;
  sensitive_content?: boolean;
  language_hints?: string[];
  bounding_polygon?: Array<{ x: number; y: number }>;
}

export interface Phase6BOCRPlaceEvidenceSummary {
  matched_entity?: string;
  normalized_name: string;
  country_code?: string | null;
  region?: string | null;
  match_type: string;
  evidence_strength: number;
  source: string;
  center?: { latitude: number; longitude: number };
  text_similarity?: number;
  ambiguity_count?: number;
  dataset_version?: string;
  license?: string;
}

export interface Phase6BOCRSummary {
  provider: string;
  status?: "completed" | "abstained" | "skipped" | "failed";
  fallback_used?: boolean;
  detections: Phase6BOCRDetectionSummary[];
  place_evidence: Phase6BOCRPlaceEvidenceSummary[];
  warnings?: string[];
  reason_code?: string | null;
}

export interface Phase6BCloudObservedClue {
  type: "text" | "road" | "sign" | "architecture" | "terrain" | "vehicle" | "other";
  observation: string;
  supports_candidate_ids: string[];
  contradicts_candidate_ids: string[];
}

export interface Phase6BCloudReview {
  decision: "support_candidate" | "reject_all" | "insufficient";
  selected_candidate_ids: string[];
  observed_clues: Phase6BCloudObservedClue[];
  uncertainty_reason: string;
  candidate_adjustments?: Array<{ candidate_id: string; adjustment: number; reason: string }>;
  suggested_place_query?: string | null;
  requires_high_detail?: boolean;
}

export interface Phase6BCloudAssistSummary {
  allowed: boolean;
  triggered: boolean;
  provider: "openai";
  model: string;
  prompt_version: "openai-geo-review-v1";
  reason?: string | null;
  reason_code?: string | null;
  status?: "completed" | "skipped" | "refused" | "failed";
  cache_hit: boolean;
  trigger_reasons?: string[];
  estimated_cost_usd: number | null;
  cost_estimate_version?: string | null;
  cost_basis?: "usage_based" | "reservation_upper_bound" | "cache_hit" | null;
  usage?: { input_tokens?: number | null; cached_input_tokens?: number | null; output_tokens?: number | null; total_tokens?: number | null } | null;
  budget?: { calls_today: number; estimated_month_spend_usd: number; configured_monthly_budget_usd: number; remaining_budget_usd: number } | null;
  monthly_budget_remaining_usd?: number | null;
  daily_calls_remaining?: number | null;
  review?: Phase6BCloudReview | null;
  warnings?: string[];
}

export interface Phase6CHierarchicalCandidateSummary {
  candidate_id: string;
  latitude: number;
  longitude: number;
  search_level: "global" | "catalogue" | "regional_refinement" | "turkiye_refinement";
  provider_rank: number;
  provider_score: number;
  score_semantics: "raw_cosine_similarity_not_confidence";
  grid_resolution_km: number;
}

export interface Phase6CMegaLocMatchSummary {
  reference_id: string;
  rank: number;
  latitude: number;
  longitude: number;
  similarity: number;
  similarity_semantics: "cosine_similarity_not_confidence";
  confidence: null;
  uncertainty_radius_m: number;
  source: "mapillary" | "kartaview" | "manual";
  source_family: string;
  source_sequence_id: string;
  source_url: string;
  captured_at: string | null;
  license: string;
  attribution: string;
}

export interface Phase6CG3ScoreSummary {
  candidate_id: string;
  rank: number;
  raw_score: number;
  score_semantics: "raw_g3_similarity_not_confidence";
}

export interface Phase6CProviderRunSummary {
  provider_id: string;
  status: "completed" | "abstained" | "skipped" | "disabled" | "unavailable" | "failed" | "timeout";
  source_revision: string | null;
  model_revision: string | null;
  duration_ms: number;
  candidates_produced: number;
  reason_code: string | null;
}

export type Phase6CEvidenceKind =
  | "geoclip_original"
  | "geoclip_hierarchical"
  | "osv_direct_regression"
  | "plonk_samples"
  | "megaloc_retrieval"
  | "g3_verification"
  | "ocr_place_match"
  | "openai_review";

export interface Phase6CFusionMemberSummary {
  evidence_kind: Phase6CEvidenceKind;
  provider: string;
  model_id: string;
  model_revision: string;
  candidate_id: string;
  source_family: string;
  correlation_group: string;
  score_semantics: string;
  raw_value: number | null;
  provider_rank: number;
  sample_support: number;
  provenance: string;
}

export interface Phase6CFusionContributionSummary {
  name: string;
  source: string;
  raw_value: number;
  normalized_value: number;
  weight: number;
  contribution: number;
  reason: string;
  independent: boolean;
  correlation_group: string;
}

export interface Phase6CFusedCandidateSummary {
  cluster_id: string;
  latitude: number;
  longitude: number;
  uncertainty_radius_km: number;
  relative_rank_score: number;
  score_semantics: "uncalibrated_relative_rank_not_probability";
  confidence: null;
  calibrated: false;
  source_family_count: number;
  independent_source_family_count: number;
  correlated_source_family_count: number;
  provider_count: number;
  spread_km: number;
  publication_eligible: boolean;
  publication_basis: "at_least_two_independent_source_families" | "candidate_recall_only_insufficient_independence";
  pre_diversity_rank: number;
  final_rank: number;
  rank_movement: number;
  movement_reasons: string[];
  members: Phase6CFusionMemberSummary[];
  contributions: Phase6CFusionContributionSummary[];
}

export interface Phase6CLeakageAuditSummary {
  status: "passed" | "failed" | "not_run" | "incomplete";
  audit_version: string;
  report_fingerprint: string | null;
  references_checked: number;
  references_excluded: number;
  reason_code: string | null;
}

export interface Phase6CAblationCandidateSummary {
  rank: number;
  latitude: number;
  longitude: number;
  uncertainty_radius_km: number;
  relative_rank_score: number;
  score_semantics: "uncalibrated_relative_rank_not_probability";
  publication_eligible: boolean;
  evidence_kinds: string[];
}

export interface Phase6CAblationSummary {
  profile_id: string;
  candidate_count: number;
  publication_candidate_count: number;
  abstained: boolean;
  abstention_reason: string | null;
  included_evidence_kinds: string[];
  excluded_evidence_kinds: string[];
  candidates: Phase6CAblationCandidateSummary[];
}

export interface Phase6CAnalysisSummary {
  schema_version: "atlaslens-phase6c-analysis-v1";
  pipeline_version: "phase6c-v1";
  fusion_version: "phase6c-v1";
  reference_index_version: string | null;
  evaluation_run_id: string | null;
  hierarchical_candidates: Phase6CHierarchicalCandidateSummary[];
  megaloc_matches: Phase6CMegaLocMatchSummary[];
  g3_scores: Phase6CG3ScoreSummary[];
  providers: Phase6CProviderRunSummary[];
  fusion_candidates: Phase6CFusedCandidateSummary[];
  publication_candidate_count: number;
  turkiye_signal_count: number;
  turkiye_signal_groups: string[];
  leakage_audit: Phase6CLeakageAuditSummary;
  reference_attributions: string[];
  ablations: Phase6CAblationSummary[];
  cache_fingerprint: string;
}

export type SystemIntelligenceModelCard = components["schemas"]["SystemIntelligenceModelCard"];
export type SystemIntelligenceReferenceIndexCard = components["schemas"]["SystemIntelligenceReferenceIndexCard"];
export type SystemIntelligenceResponse = components["schemas"]["SystemIntelligenceResponse"];

export type Candidate = Omit<GeneratedCandidate, "phase4_assessment" | "phase5b_assessment"> & {
  phase4_assessment?: Phase4Assessment | null;
  phase5b_assessment?: Phase5BAssessment | null;
  geoclip_cluster?: GeoClipClusterSummary | null;
  confidence_assessment?: UncalibratedConfidenceSummary | null;
  reverse_geocode?: ReverseGeocodeSummary | null;
};

export type Analysis = Omit<GeneratedAnalysis, "candidates" | "pipeline_version" | "phase5b_diagnostics" | "scene_analysis" | "model_predictions" | "fusion" | "ocr" | "cloud_assist" | "phase6c"> & {
  candidates: Candidate[];
  pipeline_version?: string;
  phase5b_diagnostics?: Phase5BDiagnostics | null;
  scene_analysis?: SceneSegmentationSummary | null;
  model_predictions?: Record<string, Phase6BModelPredictionSummary | null> | null;
  fusion?: Phase6BFusionSummary | null;
  ocr?: Phase6BOCRSummary | null;
  cloud_assist?: Phase6BCloudAssistSummary | null;
  phase6c?: Phase6CAnalysisSummary | null;
};

const analysisModeSchema = z.enum(["local_only", "cloud_assisted"]);
const statusSchema = z.enum(["queued", "processing", "completed", "failed", "deleted"]);
const progressSchema = z
  .object({
    stage: z.string(),
    percent: z.number().int().min(0).max(100),
    message_key: z.string(),
  })
  .strict();

const provenanceSchema = z
  .object({
    provider_id: z.string(),
    provider_kind: z.string(),
    provider_version: z.string(),
    execution_boundary: z.enum(["local", "cloud"]),
    model_name: z.string().nullable().optional(),
    output_schema_version: z.string(),
  })
  .strict();

const retrievalCoverageContextSchema: z.ZodType<RetrievalCoverageContext> = z
  .object({
    analysis_scope: z.enum(["generic_upload", "ankara_reference_pilot", "coarse_provider_routed"]),
    coverage_status: z.enum(["pilot_eligible", "insufficient", "provider_unavailable"]),
    coverage_label: z.string().min(1).max(160),
    retrieval_provider: z.string().min(1).max(160),
    retrieval_scope: z.string().min(1).max(160),
    result_semantics: z.string().min(1).max(240),
    abstained: z.boolean(),
    abstention_reason: z.string().min(1).max(120).nullable().optional(),
    similarity_semantics: z.literal("cosine_similarity_not_confidence"),
    supported_region: z.string().min(1).max(240),
    evidence_version: z.string().min(1).max(160),
    benchmark_version: z.string().min(1).max(160),
  })
  .strict();

const evidenceSchema = z
  .object({
    id: z.string(),
    type: z.string(),
    label: z.string(),
    display_value: z.string().nullable(),
    confidence: z.number().min(0).max(1).nullable(),
    confidence_basis: z.string(),
    source: z.string(),
    sensitive: z.boolean(),
    provenance: provenanceSchema,
    retrieval_context: retrievalCoverageContextSchema.nullable().optional(),
  })
  .strict();

const geoPointSchema = z
  .object({ latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180) })
  .strict();

const geoJsonPointSchema = z
  .object({
    type: z.literal("Point"),
    coordinates: z.tuple([z.number().min(-180).max(180), z.number().min(-90).max(90)]),
  })
  .strict();

const geoJsonPolygonSchema = z
  .object({
    type: z.literal("Polygon"),
    coordinates: z.array(z.array(z.tuple([z.number().min(-180).max(180), z.number().min(-90).max(90)])).min(4)).min(1),
  })
  .strict();

const phase4ScoreContributionSchema = z
  .object({
    feature: z.string().min(1).max(80),
    raw_value: z.number(),
    weight: z.number(),
    contribution: z.number(),
    reason_code: z.string().min(1).max(120),
  })
  .strict();

const mapConstraintSummarySchema = z
  .object({
    clue: z.string().min(1).max(120),
    map_feature: z.string().min(1).max(120),
    status: z.enum(["supported", "contradicted", "neutral", "unknown"]),
    reliability: z.number().min(0).max(1),
    query_radius_km: z.number().positive(),
    provider: z.string().min(1).max(80),
    limitation: z.string().max(300).nullable().optional(),
  })
  .strict();

const geometryVerificationSummarySchema = z
  .object({
    reference_id: z.string().min(1).max(128),
    provider: z.string().min(1).max(80),
    status: z.enum(["supported", "inconclusive", "contradicted", "unavailable", "failed"]),
    query_keypoints: z.number().int().min(0),
    reference_keypoints: z.number().int().min(0),
    raw_matches: z.number().int().min(0),
    filtered_matches: z.number().int().min(0),
    inliers: z.number().int().min(0),
    inlier_ratio: z.number().min(0).max(1),
    query_coverage: z.number().min(0).max(1),
    reference_coverage: z.number().min(0).max(1),
    residual_error_px: z.number().min(0).nullable().optional(),
    robust_model_type: z.enum(["homography", "fundamental_matrix"]).nullable().optional(),
    limitations: z.array(z.string()).max(12),
    runtime_ms: z.number().int().min(0),
  })
  .strict();

const referenceAttributionSchema = z
  .object({
    reference_id: z.string().min(1).max(128),
    source: z.string().min(1).max(500),
    license: z.string().min(1).max(500),
    attribution: z.string().min(1).max(500),
    display_allowed: z.boolean(),
  })
  .strict();

export const phase4AssessmentSchema: z.ZodType<Phase4Assessment> = z
  .object({
    classification: z.enum([
      "model_only",
      "retrieval_only",
      "map_supported",
      "geometry_supported",
      "multi_source_supported",
      "contradicted",
      "abstained",
    ]),
    relative_rank_score: z.number().min(0).max(1),
    score_semantics: z.literal("uncalibrated_relative_rank"),
    reranker_version: z.string().min(1).max(80),
    score_breakdown: z.array(phase4ScoreContributionSchema).max(32),
    source_diversity: z.number().int().min(0),
    contributing_retrieval_hit_ids: z.array(z.string()).max(100),
    map_observations: z.array(mapConstraintSummarySchema).max(32),
    geometry_results: z.array(geometryVerificationSummarySchema).max(16),
    contradictions: z.array(z.string()).max(24),
    reference_attributions: z.array(referenceAttributionSchema).max(16),
    limitations: z.array(z.string()).max(24),
  })
  .strict();

const phase5bScoreContributionSchema = z
  .object({
    feature: z.string().min(1).max(80),
    raw_value: z.number(),
    weight: z.number(),
    contribution: z.number(),
    reason_code: z.string().min(1).max(120),
  })
  .strict();

const placeEvidenceSummarySchema = z
  .object({
    matched_entity: z.string().min(1).max(200),
    normalized_name: z.string().min(1).max(200),
    country_code: z.string().regex(/^[A-Z]{2}$/).nullable().optional(),
    region: z.string().max(160).nullable().optional(),
    center: geoPointSchema,
    match_type: z.enum([
      "country",
      "region",
      "city",
      "district",
      "road",
      "airport",
      "station",
      "public_landmark",
      "public_institution",
      "domain_suffix",
    ]),
    text_similarity: z.number().min(0).max(1),
    ambiguity_count: z.number().int().min(1),
    evidence_strength: z.number().min(0).max(1),
    source: z.string().min(1).max(500),
    dataset_version: z.string().min(1).max(120),
    license: z.string().min(1).max(500),
  })
  .strict();

const retrievalMatchSummarySchema = z
  .object({
    reference_id: z.string().min(1).max(128),
    provider: z.string().min(1).max(80),
    source: z.string().min(1).max(500),
    distance: z.number().min(0).max(2),
    relative_similarity: z.number().min(-1).max(1),
    center: geoPointSchema,
    geographic_cluster: z.string().min(1).max(100),
    license: z.string().min(1).max(500),
    attribution: z.string().min(1).max(500),
    display_allowed: z.boolean(),
  })
  .strict();

export const phase5bAssessmentSchema: z.ZodType<Phase5BAssessment> = z
  .object({
    classification: z.enum([
      "model_only",
      "place_supported",
      "retrieval_supported",
      "map_supported",
      "multi_source_supported",
      "contradicted",
    ]),
    relative_rank_score: z.number().min(0).max(1),
    score_semantics: z.literal("uncalibrated_relative_rank"),
    reranker_version: z.enum(["phase5b-v1", "phase6a-v1", "phase6b-v1"]),
    score_breakdown: z.array(phase5bScoreContributionSchema).max(48),
    provider_diversity: z.number().int().min(0),
    source_diversity: z.number().int().min(0),
    place_matches: z.array(placeEvidenceSummarySchema).max(12),
    retrieval_matches: z.array(retrievalMatchSummarySchema).max(16),
    map_observations: z.array(mapConstraintSummarySchema).max(32),
    supports: z.array(z.string()).max(24),
    contradictions: z.array(z.string()).max(24),
    movement_reasons: z.array(z.string()).max(24),
    limitations: z.array(z.string()).max(24),
  })
  .strict();

const providerRunDiagnosticSchema = z
  .object({
    provider_id: z.string().min(1).max(80),
    provider_type: z.string().min(1).max(80),
    status: z.enum(["succeeded", "abstained", "skipped", "failed"]),
    duration_ms: z.number().int().min(0),
    reason_code: z.string().max(120).nullable().optional(),
    device: z.string().max(80).nullable().optional(),
    offline: z.boolean(),
  })
  .strict();

const referenceIndexDiagnosticSchema = z
  .object({
    status: z.enum(["ready", "unavailable", "disabled", "incompatible"]),
    index_id: z.string().max(128).nullable().optional(),
    embedding_provider: z.string().max(80).nullable().optional(),
    embedding_version: z.string().max(120).nullable().optional(),
    dimension: z.number().int().positive().nullable().optional(),
    image_count: z.number().int().min(0),
    checksum: z.string().regex(/^[a-f0-9]{64}$/).nullable().optional(),
  })
  .strict();

const phase5bDiagnosticsSchema: z.ZodType<Phase5BDiagnostics> = z
  .object({
    reranker_version: z.enum(["phase5b-v1", "phase6a-v1", "phase6b-v1"]),
    providers: z.array(providerRunDiagnosticSchema).max(16),
    reference_index: referenceIndexDiagnosticSchema.nullable().optional(),
    partial_failures: z.array(z.string()).max(24),
  })
  .strict();

const placeLabelDiagnosticsSchema = z
  .object({
    country: z.string().max(120).nullable(),
    region: z.string().max(160).nullable(),
    city: z.string().max(160).nullable(),
    distance_to_place_km: z.number().min(0),
    source: z.string().min(1).max(500),
    dataset_version: z.string().min(1).max(120),
    license: z.string().min(1).max(500),
  })
  .strict();

const modelPredictionDiagnosticsSchema = z
  .object({
    provider_id: z.string(),
    model_name: z.string(),
    model_revision: z.string(),
    implementation_revision: z.string(),
    device: z.string(),
    dtype: z.string(),
    raw_score: z.number().min(0).max(1),
    score_type: z.string().min(1).max(120).regex(/^[a-z0-9._-]+$/),
    normalization_method: z.string().min(1).max(120).regex(/^[a-z0-9._-]+$/),
    calibration_state: z.enum(["uncalibrated", "preliminary", "calibrated"]),
    original_rank: z.number().int().min(1),
    inference_ms: z.number().int().min(0),
    external_transfer: z.literal(false),
    limitations: z.array(z.string()).min(1).max(12),
    place_label: placeLabelDiagnosticsSchema.nullable().optional(),
  })
  .strict();

const sceneClassSummarySchema = z
  .object({
    class_id: z.number().int().min(0),
    class_name: z.string().min(1).max(160),
    pixel_ratio: z.number().min(0).max(1),
    percentage: z.number().min(0).max(100),
  })
  .strict();

const sceneGroupSummarySchema = z
  .object({
    name: z.string().min(1).max(80).regex(/^[a-z0-9_]+$/),
    pixel_ratio: z.number().min(0).max(1),
    percentage: z.number().min(0).max(100),
  })
  .strict();

const sceneTagSummarySchema = z
  .object({
    name: z.string().min(1).max(80).regex(/^[a-z0-9_]+$/),
    strength: z.number().min(0).max(1),
    strength_semantics: z.literal("deterministic_heuristic_not_probability"),
    reason: z.string().min(1).max(240),
  })
  .strict();

export const sceneSegmentationSummarySchema = z
  .object({
    status: z.literal("completed"),
    provider: z.string().min(1).max(80),
    device: z.string().min(1).max(80),
    inference_ms: z.number().min(0),
    image_width: z.number().int().positive(),
    image_height: z.number().int().positive(),
    semantic_label_names_available: z.boolean(),
    dominant_classes: z.array(sceneClassSummarySchema).max(24),
    scene_groups: z.array(sceneGroupSummarySchema).max(16),
    scene_tags: z.array(sceneTagSummarySchema).max(16),
    warnings: z.array(z.string()).max(20),
  })
  .strict();

export const geoClipClusterSummarySchema = z
  .object({
    cluster_id: z.string().min(1).max(128),
    source: z.literal("geoclip"),
    member_count: z.number().int().min(1).max(100),
    member_ranks: z.array(z.number().int().min(1)).min(1).max(100),
    max_raw_similarity: z.number().min(0).max(1),
    mean_raw_similarity: z.number().min(0).max(1),
    raw_score_type: z.string().min(1).max(120),
    cluster_support: z.number().min(0).max(1),
    score_semantics: z.literal("uncalibrated_relative_rank"),
  })
  .strict()
  .superRefine((cluster, context) => {
    if (cluster.member_ranks.length !== cluster.member_count) {
      context.addIssue({ code: z.ZodIssueCode.custom, message: "cluster member count and ranks must agree" });
    }
    if (new Set(cluster.member_ranks).size !== cluster.member_ranks.length) {
      context.addIssue({ code: z.ZodIssueCode.custom, message: "cluster member ranks must be unique" });
    }
  });

export const uncalibratedConfidenceSummarySchema = z
  .object({
    label: z.enum(["low", "medium", "high", "very_high"]),
    score: z.null(),
    calibrated: z.literal(false),
    basis: z.array(z.string()).min(1).max(16),
  })
  .strict();

export const reverseGeocodeSummarySchema = z
  .object({
    country: z.string().max(120).nullable(),
    country_code: z.string().regex(/^[A-Z]{2}$/).nullable(),
    region: z.string().max(160).nullable(),
    city: z.string().max(160).nullable(),
    district: z.string().max(160).nullable(),
    display_name: z.string().min(1).max(200),
    provider: z.string().min(1).max(500),
    dataset_version: z.string().min(1).max(120),
    license: z.string().min(1).max(500),
  })
  .strict();

const phase6BProviderStateSchema = z.enum(["completed", "skipped", "disabled", "failed", "timeout"]);
const phase6BSourceFamilySchema = z.enum([
  "mp16_family",
  "osv5m_family",
  "yfcc_family",
  "inat_family",
  "textual_evidence_family",
  "cloud_reasoning_family",
]);
const phase6BDiagnosticValueSchema = z.union([z.string().max(240), z.number(), z.boolean(), z.null()]);
const boundedPhase6BDiagnosticsSchema = z
  .record(phase6BDiagnosticValueSchema)
  .superRefine((value, context) => {
    if (Object.keys(value).length > 20) context.addIssue({ code: z.ZodIssueCode.custom, message: "diagnostics are bounded" });
  });

const phase6BGeographicCandidateSchema = z
  .object({
    candidate_id: z.string().min(1).max(128),
    latitude: z.number().min(-90).max(90),
    longitude: z.number().min(-180).max(180),
    raw_score: z.number().nullable(),
    provider_rank: z.number().int().min(1).max(100),
    sample_support: z.number().int().min(1).max(4096),
    metadata: boundedPhase6BDiagnosticsSchema.optional(),
  })
  .strict();

export const phase6BModelPredictionSummarySchema: z.ZodType<Phase6BModelPredictionSummary> = z
  .object({
    provider: z.string().min(1).max(80),
    model_id: z.string().min(1).max(160),
    model_revision: z.string().min(1).max(160),
    source_family: phase6BSourceFamilySchema,
    status: phase6BProviderStateSchema,
    device: z.enum(["cuda", "cpu"]),
    duration_ms: z.number().int().min(0),
    score_semantics: z.enum(["similarity", "direct_regression", "sample_density"]),
    candidates: z.array(phase6BGeographicCandidateSchema).max(100),
    warnings: z.array(z.string().max(160)).max(20),
    reason_code: z.string().min(1).max(120).nullable().optional(),
    execution_mode: z.enum(["in_process", "isolated_worker"]).nullable().optional(),
    diagnostics: boundedPhase6BDiagnosticsSchema.optional(),
  })
  .strict();

export const phase6BModelPredictionsSchema = z
  .record(phase6BModelPredictionSummarySchema.nullable())
  .superRefine((value, context) => {
    if (Object.keys(value).length > 12) context.addIssue({ code: z.ZodIssueCode.custom, message: "model predictions are bounded" });
  });

const phase6BFusionMemberSchema = z
  .object({
    provider: z.string().min(1).max(80),
    model_id: z.string().min(1).max(160),
    source_family: phase6BSourceFamilySchema,
    provider_rank: z.number().int().min(1).max(100),
    candidate_id: z.string().min(1).max(128).optional(),
    sample_support: z.number().int().min(1).max(4096).optional(),
  })
  .strict();

const phase6BFusionContributionSchema = z
  .object({
    name: z.string().min(1).max(80),
    contribution: z.number().min(-1).max(1),
    reason: z.string().min(1).max(240),
    raw_value: z.number().optional(),
    weight: z.number().optional(),
  })
  .strict();

const phase6BFusedClusterSchema = z
  .object({
    cluster_id: z.string().min(1).max(128),
    latitude: z.number().min(-90).max(90),
    longitude: z.number().min(-180).max(180),
    radius_km: z.number().positive().max(40_100),
    relative_rank_score: z.number().min(0).max(1).optional(),
    score_semantics: z.literal("uncalibrated_relative_rank_not_probability").optional(),
    provider_count: z.number().int().min(1).max(16),
    independent_family_count: z.number().int().min(1).max(6),
    same_family_duplicate_support: z.number().int().min(0).max(16),
    spread_km: z.number().min(0).max(40_100),
    members: z.array(phase6BFusionMemberSchema).min(1).max(100),
    contributions: z.array(phase6BFusionContributionSchema).max(20),
    ocr_agreement: z.boolean(),
    ocr_contradiction: z.boolean(),
  })
  .strict();

const phase6BAgreementSummarySchema = z
  .object({
    provider_count: z.number().int().min(0).max(16),
    independent_family_count: z.number().int().min(0).max(6),
    same_family_duplicate_support: z.number().int().min(0).max(16),
    geographic_disagreement: z.boolean(),
    ocr_agreement: z.boolean(),
    ocr_contradiction: z.boolean(),
  })
  .strict();

export const phase6BFusionSummarySchema: z.ZodType<Phase6BFusionSummary> = z
  .object({
    version: z.literal("phase6b-v1"),
    source_families: z.array(phase6BSourceFamilySchema).max(8),
    agreement_summary: phase6BAgreementSummarySchema,
    candidate_clusters: z.array(phase6BFusedClusterSchema).max(20),
    provider_failures: z.array(z.string().max(160)).max(24).optional(),
    abstained: z.boolean().optional(),
    warnings: z.array(z.string().max(160)).max(24).optional(),
  })
  .strict();

const phase6BOCRDetectionSchema = z
  .object({
    redacted_text: z.string().min(1).max(240),
    normalized_text: z.string().min(1).max(240).optional(),
    confidence: z.number().min(0).max(1),
    confidence_semantics: z.literal("uncalibrated_ocr_engine_score").optional(),
    script: z.string().min(1).max(40),
    provider: z.string().min(1).max(80),
    profile: z.string().min(1).max(80),
    sensitive_content: z.boolean().optional(),
    language_hints: z.array(z.string().max(40)).max(6).optional(),
    bounding_polygon: z.array(z.object({ x: z.number().min(0).max(1), y: z.number().min(0).max(1) }).strict()).length(4).optional(),
  })
  .strict();

const phase6BOCRPlaceEvidenceSchema = z
  .object({
    matched_entity: z.string().min(1).max(200).optional(),
    normalized_name: z.string().min(1).max(200),
    country_code: z.string().regex(/^[A-Z]{2}$/).nullable().optional(),
    region: z.string().max(160).nullable().optional(),
    center: geoPointSchema.optional(),
    match_type: z.string().min(1).max(40),
    text_similarity: z.number().min(0).max(1).optional(),
    ambiguity_count: z.number().int().min(1).optional(),
    evidence_strength: z.number().min(0).max(1),
    source: z.string().min(1).max(500),
    dataset_version: z.string().min(1).max(120).optional(),
    license: z.string().min(1).max(500).optional(),
  })
  .strict();

export const phase6BOCRSummarySchema: z.ZodType<Phase6BOCRSummary> = z
  .object({
    provider: z.string().min(1).max(80),
    status: z.enum(["completed", "abstained", "skipped", "failed"]).optional(),
    fallback_used: z.boolean().optional(),
    detections: z.array(phase6BOCRDetectionSchema).max(32),
    place_evidence: z.array(phase6BOCRPlaceEvidenceSchema).max(12),
    warnings: z.array(z.string().max(160)).max(20).optional(),
    reason_code: z.string().max(120).nullable().optional(),
  })
  .strict();

const phase6BCloudObservedClueSchema = z
  .object({
    type: z.enum(["text", "road", "sign", "architecture", "terrain", "vehicle", "other"]),
    observation: z.string().min(1).max(240),
    supports_candidate_ids: z.array(z.string().min(1).max(128)).max(8),
    contradicts_candidate_ids: z.array(z.string().min(1).max(128)).max(8),
  })
  .strict();

const phase6BCloudReviewSchema = z
  .object({
    decision: z.enum(["support_candidate", "reject_all", "insufficient"]),
    selected_candidate_ids: z.array(z.string().min(1).max(128)).max(8),
    candidate_adjustments: z.array(z.object({ candidate_id: z.string().min(1).max(128), adjustment: z.number().min(-0.15).max(0.15), reason: z.string().min(1).max(240) }).strict()).max(8).optional(),
    observed_clues: z.array(phase6BCloudObservedClueSchema).max(12),
    suggested_place_query: z.string().min(1).max(120).nullable().optional(),
    uncertainty_reason: z.string().min(1).max(240),
    requires_high_detail: z.boolean().optional(),
  })
  .strict();

const phase6BCloudUsageSchema = z
  .object({
    input_tokens: z.number().int().min(0).max(10_000_000).nullable().optional(),
    cached_input_tokens: z.number().int().min(0).max(10_000_000).nullable().optional(),
    output_tokens: z.number().int().min(0).max(10_000_000).nullable().optional(),
    total_tokens: z.number().int().min(0).max(20_000_000).nullable().optional(),
  })
  .strict();

const phase6BCloudBudgetSchema = z
  .object({
    calls_today: z.number().int().min(0).max(100_000),
    estimated_month_spend_usd: z.number().min(0).max(100_000),
    configured_monthly_budget_usd: z.number().positive().max(100_000),
    remaining_budget_usd: z.number().min(0).max(100_000),
  })
  .strict();

export const phase6BCloudAssistSummarySchema: z.ZodType<Phase6BCloudAssistSummary> = z
  .object({
    allowed: z.boolean(),
    triggered: z.boolean(),
    provider: z.literal("openai"),
    model: z.string().min(1).max(120),
    prompt_version: z.literal("openai-geo-review-v1"),
    reason: z.string().max(160).nullable().optional(),
    reason_code: z.string().max(160).nullable().optional(),
    status: z.enum(["completed", "skipped", "refused", "failed"]).optional(),
    cache_hit: z.boolean(),
    trigger_reasons: z.array(z.string().min(1).max(80)).max(8).optional(),
    estimated_cost_usd: z.number().min(0).max(100).nullable(),
    cost_estimate_version: z.string().min(1).max(80).nullable().optional(),
    cost_basis: z.enum(["usage_based", "reservation_upper_bound", "cache_hit"]).nullable().optional(),
    usage: phase6BCloudUsageSchema.nullable().optional(),
    budget: phase6BCloudBudgetSchema.nullable().optional(),
    monthly_budget_remaining_usd: z.number().min(0).max(10_000).nullable().optional(),
    daily_calls_remaining: z.number().int().min(0).max(10_000).nullable().optional(),
    review: phase6BCloudReviewSchema.nullable().optional(),
    warnings: z.array(z.string().max(160)).max(4).optional(),
  })
  .strict();

const phase6CEvidenceKindSchema = z.enum([
  "geoclip_original",
  "geoclip_hierarchical",
  "osv_direct_regression",
  "plonk_samples",
  "megaloc_retrieval",
  "g3_verification",
  "ocr_place_match",
  "openai_review",
]);

const phase6CHierarchicalCandidateSchema = z
  .object({
    candidate_id: z.string().min(1).max(128),
    latitude: z.number().min(-90).max(90),
    longitude: z.number().min(-180).max(180),
    search_level: z.enum(["global", "catalogue", "regional_refinement", "turkiye_refinement"]),
    provider_rank: z.number().int().min(1).max(64),
    provider_score: z.number(),
    score_semantics: z.literal("raw_cosine_similarity_not_confidence"),
    grid_resolution_km: z.number().positive(),
  })
  .strict();

const phase6CMegaLocMatchSchema = z
  .object({
    reference_id: z.string().min(1).max(160),
    rank: z.number().int().min(1).max(200),
    latitude: z.number().min(-90).max(90),
    longitude: z.number().min(-180).max(180),
    similarity: z.number().min(-1).max(1),
    similarity_semantics: z.literal("cosine_similarity_not_confidence"),
    confidence: z.null(),
    uncertainty_radius_m: z.number().positive(),
    source: z.enum(["mapillary", "kartaview", "manual"]),
    source_family: z.string().min(1).max(160),
    source_sequence_id: z.string().min(1).max(160),
    source_url: z.string().url().startsWith("https://").max(800),
    captured_at: z.string().datetime({ offset: true }).nullable(),
    license: z.string().min(1).max(500),
    attribution: z.string().min(1).max(500),
  })
  .strict();

const phase6CG3ScoreSchema = z
  .object({
    candidate_id: z.string().min(1).max(160),
    rank: z.number().int().min(1).max(256),
    raw_score: z.number(),
    score_semantics: z.literal("raw_g3_similarity_not_confidence"),
  })
  .strict();

const phase6CProviderRunSchema = z
  .object({
    provider_id: z.string().min(1).max(120),
    status: z.enum(["completed", "abstained", "skipped", "disabled", "unavailable", "failed", "timeout"]),
    source_revision: z.string().max(160).nullable(),
    model_revision: z.string().max(160).nullable(),
    duration_ms: z.number().int().min(0),
    candidates_produced: z.number().int().min(0).max(1_000),
    reason_code: z.string().max(120).nullable(),
  })
  .strict();

const phase6CFusionMemberSchema = z
  .object({
    evidence_kind: phase6CEvidenceKindSchema,
    provider: z.string().min(1).max(80),
    model_id: z.string().min(1).max(160),
    model_revision: z.string().min(1).max(160),
    candidate_id: z.string().min(1).max(128),
    source_family: z.string().min(1).max(80),
    correlation_group: z.string().min(1).max(120),
    score_semantics: z.string().min(1).max(120),
    raw_value: z.number().nullable(),
    provider_rank: z.number().int().min(1).max(256),
    sample_support: z.number().int().min(1).max(100_000),
    provenance: z.string().min(1).max(240),
  })
  .strict();

const phase6CFusionContributionSchema = z
  .object({
    name: z.string().min(1).max(80),
    source: z.string().min(1).max(120),
    raw_value: z.number(),
    normalized_value: z.number().min(0).max(1),
    weight: z.number(),
    contribution: z.number(),
    reason: z.string().min(1).max(300),
    independent: z.boolean(),
    correlation_group: z.string().min(1).max(120),
  })
  .strict();

const phase6CFusedCandidateSchema = z
  .object({
    cluster_id: z.string().min(1).max(128),
    latitude: z.number().min(-90).max(90),
    longitude: z.number().min(-180).max(180),
    uncertainty_radius_km: z.number().positive(),
    relative_rank_score: z.number().min(0).max(1),
    score_semantics: z.literal("uncalibrated_relative_rank_not_probability"),
    confidence: z.null(),
    calibrated: z.literal(false),
    source_family_count: z.number().int().min(1).max(16),
    independent_source_family_count: z.number().int().min(1).max(16),
    correlated_source_family_count: z.number().int().min(0).max(16),
    provider_count: z.number().int().min(1).max(32),
    spread_km: z.number().min(0),
    publication_eligible: z.boolean(),
    publication_basis: z.enum(["at_least_two_independent_source_families", "candidate_recall_only_insufficient_independence"]),
    pre_diversity_rank: z.number().int().min(1),
    final_rank: z.number().int().min(1).max(50),
    rank_movement: z.number().int(),
    movement_reasons: z.array(z.string()).min(1).max(4),
    members: z.array(phase6CFusionMemberSchema).min(1).max(256),
    contributions: z.array(phase6CFusionContributionSchema).min(1).max(16),
  })
  .strict();

const phase6CLeakageAuditSchema = z
  .object({
    status: z.enum(["passed", "failed", "not_run", "incomplete"]),
    audit_version: z.string().min(1).max(160),
    report_fingerprint: z.string().regex(/^[a-f0-9]{64}$/).nullable(),
    references_checked: z.number().int().min(0).max(100_000),
    references_excluded: z.number().int().min(0).max(100_000),
    reason_code: z.string().max(120).nullable(),
  })
  .strict();

const phase6CAblationCandidateSchema = z
  .object({
    rank: z.number().int().min(1).max(5),
    latitude: z.number().min(-90).max(90),
    longitude: z.number().min(-180).max(180),
    uncertainty_radius_km: z.number().positive(),
    relative_rank_score: z.number().min(0).max(1),
    score_semantics: z.literal("uncalibrated_relative_rank_not_probability"),
    publication_eligible: z.boolean(),
    evidence_kinds: z.array(z.string()).min(1).max(8),
  })
  .strict();

const phase6CAblationSchema = z
  .object({
    profile_id: z.string().regex(/^[a-z0-9][a-z0-9_]{0,79}$/),
    candidate_count: z.number().int().min(0).max(50),
    publication_candidate_count: z.number().int().min(0).max(50),
    abstained: z.boolean(),
    abstention_reason: z.string().max(120).nullable(),
    included_evidence_kinds: z.array(z.string()).max(8),
    excluded_evidence_kinds: z.array(z.string()).max(8),
    candidates: z.array(phase6CAblationCandidateSchema).max(5),
  })
  .strict();

export const phase6CAnalysisSummarySchema: z.ZodType<Phase6CAnalysisSummary> = z
  .object({
    schema_version: z.literal("atlaslens-phase6c-analysis-v1"),
    pipeline_version: z.literal("phase6c-v1"),
    fusion_version: z.literal("phase6c-v1"),
    reference_index_version: z.string().max(160).nullable(),
    evaluation_run_id: z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/).nullable(),
    hierarchical_candidates: z.array(phase6CHierarchicalCandidateSchema).max(64),
    megaloc_matches: z.array(phase6CMegaLocMatchSchema).max(200),
    g3_scores: z.array(phase6CG3ScoreSchema).max(96),
    providers: z.array(phase6CProviderRunSchema).max(20),
    fusion_candidates: z.array(phase6CFusedCandidateSchema).max(50),
    publication_candidate_count: z.number().int().min(0).max(50),
    turkiye_signal_count: z.number().int().min(0).max(8),
    turkiye_signal_groups: z.array(z.string()).max(8),
    leakage_audit: phase6CLeakageAuditSchema,
    reference_attributions: z.array(z.string()).max(20),
    ablations: z.array(phase6CAblationSchema).max(16),
    cache_fingerprint: z.string().regex(/^phase6c-v1:[a-f0-9]{64}$/),
  })
  .strict();

const systemIntelligenceStatusSchema = z.enum([
  "ready",
  "not_installed",
  "dependencies_installed",
  "weights_prepared",
  "worker_unreachable",
  "model_load_failed",
  "inference_not_verified",
  "incomplete",
  "loading",
  "failed",
  "disabled",
  "unavailable",
]);

const systemIntelligenceModelCardSchema = z
  .object({
    model_id: z.string().min(1).max(160),
    display_name: z.string().min(1).max(160),
    runtime_model_id: z.string().max(160).nullable(),
    repository_url: z.string().max(500).nullable(),
    purpose: z.string().min(1).max(300),
    enabled: z.boolean(),
    available: z.boolean(),
    status: systemIntelligenceStatusSchema,
    installed: z.boolean().nullable(),
    weights_available: z.boolean().nullable(),
    worker_reachable: z.boolean().nullable(),
    model_loaded: z.boolean().nullable(),
    load_verified: z.boolean().nullable(),
    real_inference_verified: z.boolean().nullable(),
    device: z.string().max(80).nullable(),
    execution_mode: z.enum(["in_process", "isolated_worker", "isolated_process", "cloud", "not_integrated"]),
    source_revision: z.string().max(160).nullable(),
    model_revision: z.string().max(160).nullable(),
    license: z.string().max(200).nullable(),
    last_success_at: z.string().datetime({ offset: true }).nullable(),
    last_latency_ms: z.number().int().min(0).nullable(),
    error_code: z.string().regex(/^[a-z0-9][a-z0-9._-]*$/).max(120).nullable(),
    current_participation: z.enum(["primary", "candidate", "fallback", "descriptive", "verifier", "optional_review", "shadow", "disabled", "not_integrated"]),
  })
  .strict();

const boundedCountRecord = (maximumKeys: number) => z.record(z.number().int().min(0)).superRefine((value, context) => {
  if (Object.keys(value).length > maximumKeys) {
    context.addIssue({ code: z.ZodIssueCode.custom, message: "distribution is bounded" });
  }
});

const systemIntelligenceReferenceIndexSchema = z
  .object({
    index_id: z.literal("turkiye_megaloc_reference_index"),
    enabled: z.boolean(),
    status: z.enum(["ready", "empty", "unavailable", "invalid", "disabled"]),
    reason_code: z.string().regex(/^[a-z0-9][a-z0-9_]*$/).min(1).max(80),
    index_version: z.string().max(160).nullable(),
    descriptor_version: z.string().max(160).nullable(),
    count: z.number().int().min(0),
    sequences: z.number().int().min(0),
    countries: z.number().int().min(0).nullable(),
    provinces: z.number().int().min(0).nullable(),
    images_per_province: boundedCountRecord(1_000).nullable(),
    source_distribution: boundedCountRecord(32).nullable(),
    attributions: z.array(z.string().min(1).max(500)).max(100),
    built_at: z.string().datetime({ offset: true }).nullable(),
    disk_usage_bytes: z.number().int().min(0),
    leakage_status: z.enum(["passed", "failed", "not_run", "unavailable"]),
    leakage_audit: z
      .object({
        status: z.literal("passed"),
        audit_version: z.literal("atlaslens-leakage-audit-v1"),
        audit_fingerprint: z.string().regex(/^[a-f0-9]{64}$/),
        source_report_sha256: z.string().regex(/^[a-f0-9]{64}$/),
        checked_reference_count: z.number().int().min(0),
        descriptor_checked_count: z.number().int().min(0),
        excluded_reference_count: z.number().int().min(0),
        pre_index_excluded_reference_count: z.number().int().min(0).nullable(),
      })
      .strict()
      .nullable(),
    duplicates: z.number().int().min(0).nullable(),
    excluded: z.number().int().min(0).nullable(),
    health: z.enum(["healthy", "degraded", "unavailable", "invalid", "disabled"]),
  })
  .strict();

export const systemIntelligenceResponseSchema: z.ZodType<SystemIntelligenceResponse> = z
  .object({
    active_pipeline_version: z.enum(["legacy-v1", "phase6c-v1"]),
    models: z.array(systemIntelligenceModelCardSchema).min(10).max(16),
    reference_index: systemIntelligenceReferenceIndexSchema,
  })
  .strict()
  .superRefine((value, context) => {
    const identifiers = value.models.map((model) => model.model_id);
    if (new Set(identifiers).size !== identifiers.length) {
      context.addIssue({ code: z.ZodIssueCode.custom, message: "model IDs must be unique" });
    }
  });

const candidateSchema = z
  .object({
    id: z.string(),
    rank: z.number().int().min(1),
    center: geoPointSchema,
    geometry: z.union([geoJsonPointSchema, geoJsonPolygonSchema]),
    radius_km: z.number().positive(),
    uncertainty_basis: z.string(),
    confidence: z.number().min(0).max(1).nullable(),
    confidence_kind: z.enum(["source_reliability", "uncalibrated_score", "calibrated_probability"]),
    confidence_basis: z.string(),
    granularity: z.enum(["exact_metadata", "city", "region", "country", "broad_area"]),
    country_code: z.string().regex(/^[A-Z]{2}$/).nullable().optional(),
    label: z.string().nullable().optional(),
    source: z.string(),
    evidence_ids: z.array(z.string()).min(1),
    evidence_summary: z.string(),
    provenance: z.array(provenanceSchema).min(1),
    verification_status: z.enum(["metadata_only", "unverified_model", "corroborated", "geometrically_verified"]),
    verified: z.boolean(),
    phase4_assessment: phase4AssessmentSchema.nullable().optional(),
    phase5b_assessment: phase5bAssessmentSchema.nullable().optional(),
    model_prediction: modelPredictionDiagnosticsSchema.nullable().optional(),
    geoclip_cluster: geoClipClusterSummarySchema.nullable().optional(),
    confidence_assessment: uncalibratedConfidenceSummarySchema.nullable().optional(),
    reverse_geocode: reverseGeocodeSummarySchema.nullable().optional(),
  })
  .strict();

const imageSchema = z
  .object({
    format: z.enum(["jpeg", "png", "webp"]),
    width: z.number().int().positive(),
    height: z.number().int().positive(),
    megapixels: z.number().min(0),
    sha256: z.string().regex(/^[a-f0-9]{64}$/),
    orientation_normalized: z.boolean(),
    exif_present: z.boolean(),
  })
  .strict();

const qualitySchema = z
  .object({
    blur_score: z.number().min(0).max(1),
    brightness_score: z.number().min(0).max(1),
    contrast_score: z.number().min(0).max(1),
    resolution_score: z.number().min(0).max(1),
    warnings: z.array(z.string()),
  })
  .strict();

const providerSchema = z
  .object({
    provider_id: z.string(),
    enabled: z.boolean(),
    available: z.boolean(),
    execution_boundary: z.enum(["local", "cloud"]),
    reason_code: z.string().nullable().optional(),
    installed: z.boolean().nullable().optional(),
    verified: z.boolean().nullable().optional(),
    operational_status: z.enum(["ready", "not_ready", "not_installed", "dependencies_installed", "weights_prepared", "worker_unreachable", "model_load_failed", "inference_not_verified", "incomplete", "loading", "failed", "disabled", "unavailable"]).nullable().optional(),
    model_name: z.string().nullable().optional(),
    model_revision: z.string().nullable().optional(),
    device: z.string().nullable().optional(),
    calibration_state: z.enum(["uncalibrated", "preliminary", "calibrated"]).nullable().optional(),
    provider_type: z.string().nullable().optional(),
    offline: z.boolean().nullable().optional(),
    license: z.string().nullable().optional(),
    limitation: z.string().nullable().optional(),
    weights_available: z.boolean().nullable().optional(),
    usable: z.boolean().nullable().optional(),
    execution_mode: z.enum(["in_process", "isolated_worker"]).nullable().optional(),
    source_revision: z.string().max(160).nullable().optional(),
    load_error: z.string().max(160).nullable().optional(),
    key_configured: z.boolean().nullable().optional(),
    budget_available: z.boolean().nullable().optional(),
  })
  .strict();

export const capabilitiesSchema: z.ZodType<Capabilities> = z
  .object({
    supported_formats: z.array(z.enum(["jpeg", "png", "webp"])),
    max_upload_bytes: z.number().int().positive(),
    max_decoded_pixels: z.number().int().positive(),
    enabled_analysis_modes: z.array(analysisModeSchema),
    providers: z
      .object({
        exif: providerSchema,
        quality: providerSchema,
        ocr: providerSchema,
        cloud_vision: providerSchema,
        global_geolocation: providerSchema.optional(),
        embedding: providerSchema.optional(),
        retrieval: providerSchema.optional(),
        place_research: providerSchema.optional(),
        map_research: providerSchema.optional(),
        visual_clues: providerSchema.optional(),
      })
      .catchall(providerSchema)
      .superRefine((providers, context) => {
        if (Object.keys(providers).length > 32) context.addIssue({ code: z.ZodIssueCode.custom, message: "providers are bounded" });
      }),
    retention: z
      .object({
        keep_uploads: z.boolean(),
        ttl_seconds: z.number().int().min(0),
        originals_deleted_after_analysis: z.boolean(),
      })
      .strict(),
    version: z.string(),
  })
  .strict();

const providerStatusItemSchema = z
  .object({
    provider_id: z.string().min(1).max(120),
    provider_type: z.string().min(1).max(120),
    mode: z.enum(["disabled", "shadow", "candidate", "primary"]),
    available: z.boolean(),
    status: z.enum(["ready", "not_ready", "not_installed", "dependencies_installed", "weights_prepared", "worker_unreachable", "model_load_failed", "inference_not_verified", "incomplete", "loading", "failed", "disabled", "unavailable"]),
    classification: z.enum(["real", "simulated"]),
    model_name: z.string().max(200).nullable().optional(),
    model_revision: z.string().max(200).nullable().optional(),
    device: z.string().max(80).nullable().optional(),
    calibration_state: z.enum(["uncalibrated", "preliminary", "calibrated"]).nullable().optional(),
    reason_code: z.string().max(160).nullable().optional(),
    source_family: z.string().max(120).nullable().optional(),
    selected_specialization: z.string().max(200).nullable().optional(),
    execution_mode: z.enum(["in_process", "isolated_worker"]).nullable().optional(),
    source_revision: z.string().max(200).nullable().optional(),
    weights_available: z.boolean().nullable().optional(),
    usable: z.boolean().nullable().optional(),
    load_error: z.string().max(160).nullable().optional(),
    key_configured: z.boolean().nullable().optional(),
    budget_available: z.boolean().nullable().optional(),
  })
  .strict();

export const providerStatusResponseSchema: z.ZodType<ProviderStatusResponse> = z
  .object({ providers: z.array(providerStatusItemSchema).max(100) })
  .strict();

const modelStatusItemSchema = z
  .object({
    model_id: z.string().min(1).max(160),
    model_version: z.string().max(160).nullable().optional(),
    artifact_digest: z.string().max(160).nullable().optional(),
    mode: z.enum(["disabled", "shadow", "candidate", "primary"]),
    verified: z.boolean(),
    status: z.enum(["not_registered", "registered", "verified", "invalid", "disabled"]),
    reason_code: z.string().max(160).nullable().optional(),
  })
  .strict();

export const modelStatusResponseSchema: z.ZodType<ModelStatusResponse> = z
  .object({ models: z.array(modelStatusItemSchema).max(100) })
  .strict();

export const acceptedSchema: z.ZodType<AnalysisAccepted> = z
  .object({
    id: z.string().uuid(),
    status: z.literal("queued"),
    status_url: z.string(),
    events_url: z.string(),
    delete_url: z.string(),
  })
  .strict();

export const analysisSchema: z.ZodType<Analysis> = z
  .object({
    id: z.string().uuid(),
    status: statusSchema,
    analysis_mode: analysisModeSchema,
    created_at: z.string().datetime({ offset: true }),
    expires_at: z.string().datetime({ offset: true }).nullable(),
    progress: progressSchema,
    image: imageSchema.nullable().optional(),
    quality: qualitySchema.nullable().optional(),
    evidence: z.array(evidenceSchema),
    candidates: z.array(candidateSchema),
    abstention: z
      .object({ abstained: z.literal(true), reason_code: z.string(), message_key: z.string() })
      .strict()
      .nullable()
      .optional(),
    warnings: z.array(z.string()),
    timings_ms: z.record(z.number().int().min(0)),
    fusion_policy_version: z.string(),
    pipeline_version: z.string().min(1).max(64).optional(),
    phase5b_diagnostics: phase5bDiagnosticsSchema.nullable().optional(),
    scene_analysis: sceneSegmentationSummarySchema.nullable().optional(),
    model_predictions: phase6BModelPredictionsSchema.nullable().optional(),
    fusion: phase6BFusionSummarySchema.nullable().optional(),
    ocr: phase6BOCRSummarySchema.nullable().optional(),
    cloud_assist: phase6BCloudAssistSummarySchema.nullable().optional(),
    phase6c: phase6CAnalysisSummarySchema.nullable().optional(),
    result_classification: z.enum(["real", "simulated"]),
    simulation: z
      .object({
        scenario_id: z.string().min(1).max(160),
        warning_key: z.literal("warning.simulated_development_result"),
        watermark: z.literal("SIMULATED DEVELOPMENT RESULT"),
      })
      .strict()
      .nullable()
      .optional(),
    provider_comparisons: z
      .array(
        z
          .object({
            provider_id: z.string().min(1).max(120),
            mode: z.enum(["shadow", "candidate"]),
            status: z.enum(["succeeded", "abstained", "skipped", "failed"]),
            runtime_ms: z.number().int().min(0),
            distance_to_primary_km: z.number().min(0).nullable().optional(),
            candidate_overlap: z.number().int().min(0).max(100).nullable().optional(),
            ranking_impact: z.enum(["none", "eligible_not_applied"]),
            failure_code: z.string().max(160).nullable().optional(),
          })
          .strict(),
      )
      .max(32)
      .optional(),
    failure: z
      .object({ code: z.string(), message_key: z.string(), retryable: z.boolean() })
      .strict()
      .nullable()
      .optional(),
  })
  .strict();

export const analysisHistoryPageSchema: z.ZodType<AnalysisHistoryPage> = z
  .object({
    items: z
      .array(
        z
          .object({
            id: z.string().uuid(),
            created_at: z.string().datetime({ offset: true }),
            expires_at: z.string().datetime({ offset: true }).nullable(),
            status: statusSchema,
            analysis_mode: analysisModeSchema,
            result_classification: z.enum(["real", "simulated"]),
            image_sha256: z.string().regex(/^[a-f0-9]{64}$/).nullable().optional(),
            image_width: z.number().int().positive().nullable().optional(),
            image_height: z.number().int().positive().nullable().optional(),
            provider_ids: z.array(z.string().min(1).max(120)).max(32),
            primary_label: z.string().max(240).nullable().optional(),
            candidate_count: z.number().int().min(0),
            evidence_count: z.number().int().min(0),
            runtime_ms: z.number().int().min(0).nullable().optional(),
            warning_count: z.number().int().min(0),
            source_retained: z.boolean(),
            deletion_state: z.literal("active"),
          })
          .strict(),
      )
      .max(500),
    total: z.number().int().min(0),
    limit: z.number().int().positive(),
    offset: z.number().int().min(0),
  })
  .strict();

const ratioViewSchema = z
  .object({
    numerator: z.number().int().min(0),
    denominator: z.number().int().min(0),
    value: z.number().min(0).max(1).nullable(),
  })
  .strict();

export const evaluationReportSummarySchema: z.ZodType<EvaluationReportSummary> = z
  .object({
    report_id: z.string().min(1).max(160),
    provider_id: z.string().min(1).max(160),
    model_revision: z.string().min(1).max(200),
    evaluation_fingerprint: z.string().min(1).max(200),
    image_count: z.number().int().min(0),
    calibration_state: z.enum(["uncalibrated", "preliminary", "calibrated"]),
    country_top1: ratioViewSchema,
    country_top5: ratioViewSchema,
    region_top1: ratioViewSchema,
    city_top1: ratioViewSchema,
    recall_top1: z.record(ratioViewSchema),
    mean_error_km: z.number().min(0).nullable().optional(),
    median_error_km: z.number().min(0).nullable().optional(),
    p95_error_km: z.number().min(0).nullable().optional(),
    abstention: ratioViewSchema,
    provider_failure: ratioViewSchema,
    latency_median_ms: z.number().min(0).nullable().optional(),
    latency_p95_ms: z.number().min(0).nullable().optional(),
    uncertainty_coverage: ratioViewSchema,
    geographic_distribution: z.record(z.number().int().min(0)),
    scene_distribution: z.record(z.number().int().min(0)),
    exclusions: z.record(z.number().int().min(0)),
    limitations: z.array(z.string().max(500)).max(100),
  })
  .strict();

export const evaluationReportListSchema: z.ZodType<EvaluationReportList> = z
  .object({ reports: z.array(evaluationReportSummarySchema).max(500) })
  .strict();

const datasetQaReportSummarySchema: z.ZodType<DatasetQAReportSummary> = z
  .object({
    report_id: z.string().min(1).max(160),
    schema_version: z.literal(1),
    dataset_fingerprint: z.string().min(1).max(200),
    dataset_type: z.enum(["geolocation", "segmentation", "mixed"]),
    created_at: z.string().datetime({ offset: true }),
    scanned_images: z.number().int().min(0),
    scanned_masks: z.number().int().min(0),
    error_count: z.number().int().min(0),
    warning_count: z.number().int().min(0),
  })
  .strict();

export const datasetQaReportListSchema: z.ZodType<DatasetQAReportList> = z
  .object({ reports: z.array(datasetQaReportSummarySchema).max(500) })
  .strict();

export const datasetQaReportSchema: z.ZodType<DatasetQAReport> = z
  .object({
    summary: datasetQaReportSummarySchema,
    checks: z.record(z.enum(["passed", "failed", "warning", "unavailable"])),
    distributions: z.record(z.record(z.number())),
    issues: z
      .array(
        z
          .object({
            code: z.string().min(1).max(160),
            severity: z.enum(["error", "warning", "info"]),
            asset_key: z.string().min(1).max(240),
            field: z.string().max(160).nullable().optional(),
            message_key: z.string().min(1).max(240),
            safe_metrics: z.record(z.string().max(240)),
          })
          .strict(),
      )
      .max(5000),
    outputs: z.array(z.string().max(500)).max(100),
    limitations: z.array(z.string().max(500)).max(100),
  })
  .strict();

const casePurposeSchema = z.enum([
  "journalism",
  "humanitarian",
  "disaster_response",
  "insurance",
  "authorized_security_research",
  "other",
]);
const caseStatusSchema = z.enum(["open", "under_review", "resolved", "archived"]);
const caseSensitivitySchema = z.enum(["standard", "sensitive", "conflict_related"]);
const adjudicationDecisionSchema = z.enum(["accepted", "rejected", "needs_more_evidence", "withdrawn"]);
const caseHashSchema = z.string().regex(/^[a-f0-9]{64}$/i);
const caseTimestampSchema = z.string().datetime({ offset: true });

export const investigationCaseSchema: z.ZodType<InvestigationCase> = z
  .object({
    id: z.string().uuid(),
    workspace_id: z.string().min(1).max(128),
    title: z.string().min(1).max(160),
    description: z.string().max(2000).nullable(),
    purpose: casePurposeSchema,
    purpose_detail: z.string().min(1).max(500).nullable(),
    source_context: z.string().min(1).max(1000),
    status: caseStatusSchema,
    sensitivity: caseSensitivitySchema,
    authorization_attested: z.boolean(),
    retention_policy: z.string().min(1).max(160),
    created_at: caseTimestampSchema,
    updated_at: caseTimestampSchema,
    closed_at: caseTimestampSchema.nullable(),
    created_by_actor_id: z.string().min(1).max(120),
    version: z.number().int().positive(),
    media_count: z.number().int().min(0),
    evidence_count: z.number().int().min(0),
    hypothesis_count: z.number().int().min(0),
    adjudication_count: z.number().int().min(0),
    latest_adjudication_decision: adjudicationDecisionSchema.nullable(),
  })
  .strict();

export const casePageSchema: z.ZodType<CasePage> = z
  .object({
    items: z.array(investigationCaseSchema).max(100),
    total: z.number().int().min(0),
    limit: z.number().int().min(1).max(100),
    offset: z.number().int().min(0),
    ordering: z.literal("updated_at_desc_id_desc"),
  })
  .strict();

export const caseMediaSchema: z.ZodType<CaseMedia> = z
  .object({
    id: z.string().uuid(),
    case_id: z.string().uuid(),
    analysis_id: z.string().uuid().nullable(),
    media_type: z.literal("image"),
    source_type: z.enum(["upload", "source_url", "external_archive", "other"]),
    original_filename_display: z.string().min(1).max(160),
    mime_type: z.enum(["image/jpeg", "image/png", "image/webp"]),
    byte_size: z.number().int().positive().max(104857600),
    sha256: caseHashSchema,
    captured_at: caseTimestampSchema.nullable(),
    received_at: caseTimestampSchema,
    source_url: z.string().url().max(800).nullable(),
    archive_url: z.string().url().max(800).nullable(),
    source_description: z.string().min(1).max(1000).nullable(),
    authorization_attested: z.boolean(),
    storage_state: z.enum(["ephemeral", "deleted_after_analysis", "unavailable", "externally_managed"]),
    created_at: caseTimestampSchema,
    analysis_status_at_link: z.string().min(1).max(40).nullable(),
    analysis_created_at: caseTimestampSchema.nullable(),
    analysis_expires_at: caseTimestampSchema.nullable(),
    materialized_at: caseTimestampSchema.nullable(),
  })
  .strict();

export const caseMediaPageSchema: z.ZodType<CaseMediaPage> = z
  .object({
    items: z.array(caseMediaSchema).max(100),
    total: z.number().int().min(0),
    limit: z.number().int().min(1).max(100),
    offset: z.number().int().min(0),
    ordering: z.literal("created_at_asc_id_asc"),
  })
  .strict();

export const caseEvidenceRecordSchema: z.ZodType<CaseEvidenceRecord> = z
  .object({
    id: z.string().uuid(),
    case_id: z.string().uuid(),
    media_id: z.string().uuid(),
    analysis_id: z.string().uuid(),
    evidence_type: z.enum(["metadata", "ocr", "visual_clue", "model_hypothesis", "retrieval_match", "map_evidence", "analyst_note"]),
    provider: z.string().min(1).max(160),
    provider_family: z.string().min(1).max(160),
    summary: z.string().min(1).max(2000),
    structured_payload: z.record(z.unknown()),
    provenance: z.record(z.unknown()),
    observed_at: caseTimestampSchema,
    created_at: caseTimestampSchema,
    immutable_source_hash: caseHashSchema,
  })
  .strict();

export const caseEvidencePageSchema: z.ZodType<CaseEvidencePage> = z
  .object({
    items: z.array(caseEvidenceRecordSchema).max(100),
    total: z.number().int().min(0),
    limit: z.number().int().min(1).max(100),
    offset: z.number().int().min(0),
    ordering: z.literal("created_at_asc_id_asc"),
  })
  .strict();

export const caseAdjudicationSchema: z.ZodType<CaseAdjudication> = z
  .object({
    id: z.string().uuid(),
    case_id: z.string().uuid(),
    hypothesis_id: z.string().uuid(),
    actor_id: z.string().min(1).max(120),
    decision: adjudicationDecisionSchema,
    rationale: z.string().min(1).max(2000),
    created_at: caseTimestampSchema,
    supersedes_adjudication_id: z.string().uuid().nullable(),
  })
  .strict();

export const locationHypothesisSchema: z.ZodType<LocationHypothesis> = z
  .object({
    id: z.string().uuid(),
    case_id: z.string().uuid(),
    media_id: z.string().uuid(),
    analysis_id: z.string().uuid().nullable(),
    origin: z.enum(["model", "operator_correction", "imported"]),
    latitude: z.number().min(-90).max(90),
    longitude: z.number().min(-180).max(180),
    uncertainty_radius_m: z.number().positive(),
    country_code: z.string().regex(/^[A-Z]{2}$/).nullable(),
    region_name: z.string().min(1).max(160).nullable(),
    locality_name: z.string().min(1).max(160).nullable(),
    rank: z.number().int().positive().nullable(),
    confidence_label: z.string().min(1).max(80).nullable(),
    calibration_state: z.enum(["calibrated", "uncalibrated", "not_applicable"]),
    supporting_evidence_ids: z.array(z.string().uuid()).max(256),
    model_family_groups: z.array(z.string().min(1).max(120)).max(32),
    created_at: caseTimestampSchema,
    supersedes_hypothesis_id: z.string().uuid().nullable(),
    latest_adjudication: caseAdjudicationSchema.nullable(),
    adjudications: z.array(caseAdjudicationSchema).max(100),
    adjudication_count: z.number().int().min(0),
  })
  .strict();

export const caseHypothesisPageSchema: z.ZodType<CaseHypothesisPage> = z
  .object({
    items: z.array(locationHypothesisSchema).max(100),
    total: z.number().int().min(0),
    limit: z.number().int().min(1).max(100),
    offset: z.number().int().min(0),
    ordering: z.literal("created_at_asc_id_asc"),
  })
  .strict();

export const caseAuditEventSchema: z.ZodType<CaseAuditEvent> = z
  .object({
    id: z.string().uuid(),
    case_id: z.string().uuid(),
    sequence_number: z.number().int().positive(),
    event_type: z.string().min(1).max(120),
    actor_id: z.string().min(1).max(120),
    actor_type: z.enum(["operator", "system", "model"]),
    payload: z.record(z.unknown()),
    created_at: caseTimestampSchema,
    previous_event_hash: caseHashSchema.nullable(),
    event_hash: caseHashSchema,
  })
  .strict();

export const caseAuditEventPageSchema: z.ZodType<CaseAuditEventPage> = z
  .object({
    items: z.array(caseAuditEventSchema).max(100),
    total: z.number().int().min(0),
    limit: z.number().int().min(1).max(100),
    offset: z.number().int().min(0),
    ordering: z.literal("sequence_number_asc"),
    integrity_scope: z.literal("tamper_evident_application_history"),
  })
  .strict();

export const caseAuditIntegritySchema: z.ZodType<CaseAuditIntegrity> = z
  .object({
    case_id: z.string().uuid(),
    valid: z.boolean(),
    checked_event_count: z.number().int().min(0),
    first_invalid_sequence: z.number().int().positive().nullable(),
    reason: z.string().min(1).max(160).nullable(),
    integrity_scope: z.literal("tamper_evident_application_history"),
    legally_certified_evidence: z.literal(false),
  })
  .strict();

export const caseMaterializationResultSchema: z.ZodType<CaseMaterializationResult> = z
  .object({
    case_id: z.string().uuid(),
    media_id: z.string().uuid(),
    analysis_id: z.string().uuid(),
    created: z.boolean(),
    evidence_created: z.number().int().min(0),
    hypotheses_created: z.number().int().min(0),
    already_materialized: z.boolean(),
    evidence_ids: z.array(z.string().uuid()).max(10000),
    hypothesis_ids: z.array(z.string().uuid()).max(1000),
  })
  .strict();

export const operatorHypothesisResultSchema: z.ZodType<OperatorHypothesisResult> = z
  .object({
    hypothesis: locationHypothesisSchema,
    adjudication: caseAdjudicationSchema,
  })
  .strict();

export const eventSchema: z.ZodType<AnalysisEvent> = z
  .object({
    event_id: z.string(),
    event_type: z.enum(["progress", "heartbeat", "completed", "failed", "deleted"]),
    analysis_id: z.string().uuid(),
    occurred_at: z.string().datetime({ offset: true }),
    status: statusSchema,
    progress: progressSchema.nullable().optional(),
  })
  .strict();

export const problemSchema: z.ZodType<ProblemDetails> = z
  .object({
    type: z.string(),
    title: z.string(),
    status: z.number().int().min(400).max(599),
    code: z.string(),
    message_key: z.string(),
    request_id: z.string(),
    retry_after_seconds: z.number().int().min(0).nullable().optional(),
  })
  .strict();
